package com.yjiyun.chatflows.manager.matrix;
import com.fasterxml.jackson.databind.*; import java.io.IOException; import java.net.URI; import java.net.http.*; import java.util.concurrent.atomic.AtomicReference;
/** Holds the Matrix access token and refreshes it through authenticated Controller API. */
public final class MatrixTokenProvider {
 private static final ObjectMapper JSON=new ObjectMapper(); private final AtomicReference<String> token; private final URI controller,matrix; private final String controllerToken,userId,password; private final HttpClient http;
 public MatrixTokenProvider(String initial,URI controller,String controllerToken){this(initial,controller,controllerToken,null,null,null,HttpClient.newHttpClient());}
 public MatrixTokenProvider(String initial,URI controller,String controllerToken,URI matrix,String userId,String password){this(initial,controller,controllerToken,matrix,userId,password,HttpClient.newHttpClient());}
 MatrixTokenProvider(String initial,URI controller,String controllerToken,URI matrix,String userId,String password,HttpClient http){if(controllerToken==null||controllerToken.isBlank())throw new IllegalArgumentException("Controller token required");this.controller=controller;this.controllerToken=controllerToken;this.matrix=matrix;this.userId=blankToNull(userId);this.password=blankToNull(password);this.http=http;if((initial==null||initial.isBlank())&&(this.matrix==null||this.userId==null||this.password==null))throw new IllegalArgumentException("Matrix access token or user/password required");token=new AtomicReference<>(initial==null?"":initial);}
 public synchronized void initialize()throws IOException,InterruptedException{if(token.get().isBlank())token.set(passwordLogin());}
 public String current(){return token.get();}
 public synchronized String refresh()throws IOException,InterruptedException{if(matrix!=null&&userId!=null&&password!=null){String fresh=passwordLogin();token.set(fresh);return fresh;}HttpRequest req=HttpRequest.newBuilder(controller.resolve("/api/v1/credentials/matrix-token")).header("Authorization","Bearer "+controllerToken).POST(HttpRequest.BodyPublishers.noBody()).build();HttpResponse<String> r=http.send(req,HttpResponse.BodyHandlers.ofString());if(r.statusCode()/100!=2)throw new IOException("Matrix token refresh failed: "+r.statusCode());JsonNode n=JSON.readTree(r.body());String fresh=token(n);token.set(fresh);return fresh;}
 private String passwordLogin()throws IOException,InterruptedException{HttpRequest request=HttpRequest.newBuilder(matrix.resolve("/_matrix/client/v3/login")).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(passwordLoginBody(userId,password))).build();HttpResponse<String> response=http.send(request,HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100!=2)throw new IOException("Matrix password login failed: "+response.statusCode());return passwordLoginToken(response.body(),userId);}
 public static String passwordLoginBody(String userId,String password){if(userId==null||userId.isBlank()||password==null||password.isBlank())throw new IllegalArgumentException("Matrix user/password required");var body=JSON.createObjectNode();body.put("type","m.login.password");body.set("identifier",JSON.createObjectNode().put("type","m.id.user").put("user",userId));body.put("password",password);return body.toString();}
 public static String passwordLoginToken(String response,String expectedUserId)throws IOException{JsonNode parsed=JSON.readTree(response);String actual=text(parsed,"user_id");if(actual==null||!actual.equals(expectedUserId))throw new IOException("Matrix login identity mismatch");return token(parsed);}
 private static String token(JsonNode n)throws IOException{String fresh=text(n,"access_token");if(fresh==null)fresh=text(n,"token");if(fresh==null)fresh=text(n,"matrix_token");if(fresh==null||fresh.isBlank())throw new IOException("Matrix token response missing token");return fresh;}
 private static String blankToNull(String value){return value==null||value.isBlank()?null:value;}
 private static String text(JsonNode n,String key){JsonNode value=n.get(key);if(value==null&&n.path("data").isObject())value=n.path("data").get(key);return value!=null&&value.isTextual()?value.asText():null;}
}
