import 'reflect-metadata';
import { HttpException } from '@nestjs/common'; import { NestFactory } from '@nestjs/core'; import { AppWebModule } from '../src/app-web.module'; import { BlueprintAdminController } from '../src/artifacts/blueprint-admin.controller'; import { McpController } from '../src/mcp/mcp.controller'; import { PipelineController } from '../src/orchestration/pipeline.controller'; import { WizardController } from '../src/web/wizard.controller'; import { WebAuthService } from '../src/web/web-auth.service';
function status(action:()=>unknown){try{action();}catch(error){return error instanceof HttpException?error.getStatus():undefined;}return undefined;}
async function main(){
 process.env.WEB_AUTH_CREDENTIALS=JSON.stringify([{token:'tenant-a-token-0123456789',client_code:'acme_beauty',actor:'@alice:local',roles:['user']},{token:'tenant-b-token-0123456789',client_code:'acme_edu',roles:['user','admin']}]);
 const auth=new WebAuthService();if(status(()=>auth.require({}))!==401)throw new Error('missing token accepted');if(status(()=>auth.require({authorization:'Bearer tenant-a-token-0123456789','x-role':'admin','x-actor':'@alice:local'}))!==403)throw new Error('wrong role accepted');if(status(()=>auth.require({authorization:'Bearer tenant-a-token-0123456789','x-role':'user','x-actor':'@mallory:local'}))!==403)throw new Error('wrong actor accepted');
 const app=await NestFactory.createApplicationContext(AppWebModule,{logger:false}),controller=app.get(WizardController),a={'authorization':'Bearer tenant-a-token-0123456789','x-role':'user','x-actor':'@alice:local'},b={'authorization':'Bearer tenant-b-token-0123456789','x-role':'user','x-actor':'@bob:local'};const turn=await controller.create(a,{client_code:'acme_edu',llm:false});if(turn.client_code!=='acme_beauty')throw new Error('body tenant overrode credential');let hidden=false;try{await controller.snapshot(b,turn.session_id);}catch(error){hidden=error instanceof HttpException&&error.getStatus()===404;}if(!hidden)throw new Error('tenant B read tenant A session');if(!app.get(PipelineController,{strict:false}))throw new Error('BFF pipeline controller missing');for(const forbidden of [McpController,BlueprintAdminController]){let exposed=true;try{app.get(forbidden,{strict:false});}catch{exposed=false;}if(exposed)throw new Error('BFF exposed '+forbidden.name);}await app.close();console.log('[PASS] Web auth binds tenant, isolates sessions and exposes BFF without MCP/Admin controllers');
}
main().then(()=>process.exit(0)).catch(error=>{console.error(error);process.exit(1);});
