import 'reflect-metadata';
import { randomUUID } from 'crypto';
import { NestFactory } from '@nestjs/core';
import { AppMcpModule } from '../src/app-mcp.module';
import { ArtifactStoreService } from '../src/artifacts/artifact-store.service';
import { ProductPhase } from '../src/common/product-phase';
import { runtimeSafeId } from '../src/common/runtime-id';
import { McpController } from '../src/mcp/mcp.controller';
import { PipelineController } from '../src/orchestration/pipeline.controller';

async function main(){
 process.env.MCP_SERVER_TOKEN='worker-mcp-e2e-token-0123456789';
 process.env.ORCHESTRATION_MODE='platform';
 process.env.PIPELINE_CONTROL_TOKEN='pipeline-human-token-0123456789';process.env.PIPELINE_APPROVAL_SIGNING_SECRET='approval-signing-secret-at-least-32-characters';
 const app=await NestFactory.createApplicationContext(AppMcpModule,{logger:false}),mcp=app.get(McpController),human=app.get(PipelineController),store=app.get(ArtifactStoreService);if((process.env.ARTIFACT_STORE??'file').toLowerCase()==='file')await store.reset();
 const auth={authorization:'Bearer '+process.env.MCP_SERVER_TOKEN};
 const triage=(memory=false)=>({scene_id:'beauty_wecom_cs',agent_family:'customer_success',channel:'wecom',industry:'beauty',confidence:0.95,reason:'Worker MCP E2E',known_slots:{industry:'beauty',role:'customer_success',desired_capabilities:['faq_retrieve','human_escalate']},can_generate_v0:true,needs_long_term_memory:memory});
 const task=(clientCode:string)=>{const runId=randomUUID(),ctx={run_id:runId,client_code:clientCode,request_id:randomUUID(),traceparent:'00-0123456789abcdef0123456789abcdef-0123456789abcdef-01'};const call=async(server:string,name:string,args:Record<string,unknown>)=>{const response:any=await mcp.rpc(server,{jsonrpc:'2.0',id:randomUUID(),method:'tools/call',params:{name,arguments:{...args,_ctx:ctx}}},auth);if(response.error)throw new Error(server+'.'+name+': '+response.error.message);const sc=response.result.structuredContent;return Array.isArray(sc?.items)?sc.items:sc;};return{runId,ctx,call};};

 const build=async(clientCode:string,memory=false)=>{const t=task(clientCode),input=triage(memory);const p1:any=await t.call('chatflows-p1','buildPhase1Result',{clientCode,triage:input});if(p1.gate!=='PASS')throw new Error('P1 did not PASS');const p2:any=await t.call('chatflows-p2','match',{clientCode,triage:input});await t.call('chatflows-p3','deriveGuidance',{triage:input});return{...t,input,p2};};
 const forceP3b=async(built:Awaited<ReturnType<typeof build>>)=>{
  if(built.p2.action!=='custom'||built.p2.build_path!=='P3C')throw new Error('default custom routing must be P3C, got '+built.p2.build_path);
  await store.updateRun(built.runId,{build_path:'P3B',current_phase:ProductPhase.P3B_FLOW_GENERATE,status:'RUNNING'});
  return built;
 };
 const approve=async(t:ReturnType<typeof task>,path:string)=>{const pendingRpc:any=await mcp.rpc('chatflows-p4',{jsonrpc:'2.0',id:randomUUID(),method:'tools/call',params:{name:'import',arguments:{runId:t.runId,clientCode:t.ctx.client_code,path,_ctx:t.ctx}}},auth),pending=pendingRpc.result?.structuredContent;if(pending?.status!=='pending_approval'||!pending.approval_id||pendingRpc.result?._meta?.approval_id!==pending.approval_id||pendingRpc.result?._meta?.approval_state!=='pending_approval')throw new Error(path+' did not expose pending approval telemetry');const signed:any=await human.decide({authorization:'Bearer pipeline-human-token-0123456789','x-role':'human','x-actor':'@human:local'},t.runId,{approved:true,approval_id:pending.approval_id});const importRpc:any=await mcp.rpc('chatflows-p4',{jsonrpc:'2.0',id:randomUUID(),method:'tools/call',params:{name:'import',arguments:{runId:t.runId,clientCode:t.ctx.client_code,path,approval:signed.approval,_ctx:t.ctx}}},auth),imported=importRpc.result?.structuredContent;if(importRpc.result?._meta?.approval_id!==pending.approval_id||importRpc.result?._meta?.approval_state!=='approved')throw new Error(path+' approval telemetry did not correlate turns');return{pending,signed,imported};};

 const p3=await build('acme_beauty');if(p3.p2.action!=='hit'||p3.p2.build_path!=='P3')throw new Error('P2 did not route P3');await p3.call('chatflows-p3','injectSections',{match:p3.p2,guidance:{}});const p3check:any=await p3.call('chatflows-p3','writeBack',{package:{}});if(!p3check.check.ok||p3check.check.checks.length!==11)throw new Error('P3 selfcheck failed');const p3import=await approve(p3,'P3');await p3.call('chatflows-p4','bindProject',{clientCode:p3.ctx.client_code,userId:'p3-user',externalId:p3import.imported.external_id,path:'P3'});const p3done:any=await p3.call('chatflows-p4','dryRun',{path:'P3',userId:'p3-user'});if(p3done.status!=='SUCCEEDED')throw new Error('P3 P4 failed');

 const p3b=await forceP3b(await build('acme_beauty_missing_kb'));await p3b.call('chatflows-p3b','generate',{triage:p3b.input,guidance:{}});const p3bcheck:any=await p3b.call('chatflows-p3b','selfcheck',{yaml:{}});if(!p3bcheck.ok||p3bcheck.checks.length!==11)throw new Error('P3B selfcheck failed');const p3bimport=await approve(p3b,'P3B');const replay:any=await mcp.rpc('chatflows-p4',{jsonrpc:'2.0',id:randomUUID(),method:'tools/call',params:{name:'import',arguments:{runId:p3b.runId,clientCode:p3b.ctx.client_code,path:'P3B',approval:p3bimport.signed.approval,_ctx:p3b.ctx}}},auth);if(!replay.error?.message.includes('already consumed'))throw new Error('approval replay accepted');const forged:any=await mcp.rpc('chatflows-p4',{jsonrpc:'2.0',id:randomUUID(),method:'tools/call',params:{name:'import',arguments:{runId:p3b.runId,clientCode:p3b.ctx.client_code,path:'P3B',approval:{...p3bimport.signed.approval,proof:'forged.token'},_ctx:p3b.ctx}}},auth);if(!forged.error?.message.includes('proof'))throw new Error('forged approval accepted');await p3b.call('chatflows-p4','bindProject',{clientCode:p3b.ctx.client_code,userId:'p3b-user',externalId:p3bimport.imported.external_id,path:'P3B'});const p3bdone:any=await p3b.call('chatflows-p4','dryRun',{path:'P3B',userId:'p3b-user'});if(p3bdone.status!=='SUCCEEDED')throw new Error('P3B P4 failed');

 const p3c=await build('acme_beauty_missing_kb',true);if(p3c.p2.build_path!=='P3C')throw new Error('P2 did not route P3C');const guidance:any=(await store.latestArtifact(p3c.runId,'guidance'))!.payload,persona=await p3c.call('chatflows-p3c','renderPersona',{guidance}),skills=await p3c.call('chatflows-p3c','listSkillCandidates',{industry:'beauty',scenarios:['beauty_wecom_cs']}),tools=await p3c.call('chatflows-p3c','listToolCandidates',{clientCode:p3c.ctx.client_code}),business={scenarios:['beauty_wecom_cs'],conditions:[...guidance.conditions,'EXPERT_BUSINESS_RULE'],escalationConditions:guidance.escalation_conditions};const blueprint:any=await p3c.call('chatflows-p3c','composeBlueprint',{persona,business,skills,tools});if(!blueprint.prompt.agentsMd.includes('EXPERT_BUSINESS_RULE')||!blueprint.tools.allow.includes('crm_query')||blueprint.tools.mcpServers[0]?.name!=='business-tools'||blueprint.skills.length!==skills.length||blueprint.prompt.soulMd!==persona.soulMd)throw new Error('P3C did not consume all four expert results');const bpCheck:any=await p3c.call('chatflows-p3c','blueprintSelfcheck',{blueprint});if(!bpCheck.ok||bpCheck.checks.length!==13)throw new Error('P3C selfcheck failed');await p3c.call('chatflows-p3c','persistBlueprint',{runId:p3c.runId,blueprint});const p3cimport=await approve(p3c,'P3C');if(p3cimport.imported.kind!=='blueprint'||p3cimport.imported.status!=='STAGED')throw new Error('P3C not staged');await p3c.call('chatflows-p4','bindProject',{clientCode:p3c.ctx.client_code,userId:'p3c-user',externalId:p3cimport.imported.external_id,path:'P3C'});
 await p3c.call('chatflows-p4','bindProject',{clientCode:p3c.ctx.client_code,userId:'@developer:local',externalId:p3cimport.imported.external_id,path:'P3C'});
 const runtimeAvailable=Boolean(process.env.AGENT_RUNTIME_URL?.trim()&&process.env.AGENT_RUNTIME_TOKEN?.trim());if(runtimeAvailable){const done:any=await p3c.call('chatflows-p4','dryRun',{path:'P3C',userId:'p3c-user'});if(done.status!=='SUCCEEDED'||!done.dry_run?.ok)throw new Error('P3C runtime dry-run failed');}

 const tampered=await build('acme_beauty_missing_kb',true),tamperGuidance:any=(await store.latestArtifact(tampered.runId,'guidance'))!.payload,tamperPersona=await tampered.call('chatflows-p3c','renderPersona',{guidance:tamperGuidance}),tamperSkills=await tampered.call('chatflows-p3c','listSkillCandidates',{industry:'beauty',scenarios:['beauty_wecom_cs']}),tamperTools=await tampered.call('chatflows-p3c','listToolCandidates',{clientCode:tampered.ctx.client_code}),tamperBusiness={conditions:tamperGuidance.conditions,escalationConditions:tamperGuidance.escalation_conditions};const checkedBlueprint:any=await tampered.call('chatflows-p3c','composeBlueprint',{persona:tamperPersona,business:tamperBusiness,skills:tamperSkills,tools:tamperTools});await tampered.call('chatflows-p3c','blueprintSelfcheck',{blueprint:checkedBlueprint});await tampered.call('chatflows-p3c','persistBlueprint',{runId:tampered.runId,blueprint:checkedBlueprint});await store.putArtifact(tampered.runId,'blueprint',{...checkedBlueprint,prompt:{...checkedBlueprint.prompt,agentsMd:checkedBlueprint.prompt.agentsMd+'\nUNREVIEWED_MUTATION'}},'blueprint-compose');const tamperPending:any=await tampered.call('chatflows-p4','import',{runId:tampered.runId,clientCode:tampered.ctx.client_code,path:'P3C'}),tamperSigned:any=await human.decide({authorization:'Bearer pipeline-human-token-0123456789','x-role':'human','x-actor':'@human:local'},tampered.runId,{approved:true,approval_id:tamperPending.approval_id});const tamperResponse:any=await mcp.rpc('chatflows-p4',{jsonrpc:'2.0',id:randomUUID(),method:'tools/call',params:{name:'import',arguments:{runId:tampered.runId,clientCode:tampered.ctx.client_code,path:'P3C',approval:tamperSigned.approval,_ctx:tampered.ctx}}},auth);if(!tamperResponse.error?.message.includes('selfcheck subject mismatch')||(await store.getRun(tampered.runId)).status!=='FAILED'||(await store.findBlueprint(checkedBlueprint.blueprintId,tampered.ctx.client_code))?.status!=='DRAFT')throw new Error('tampered post-check Blueprint reached P4 side effects');

 const deniedRun=await forceP3b(await build('acme_beauty_missing_kb'));await deniedRun.call('chatflows-p3b','generate',{triage:deniedRun.input,guidance:{}});await deniedRun.call('chatflows-p3b','selfcheck',{yaml:{}});const denyPending:any=await deniedRun.call('chatflows-p4','import',{runId:deniedRun.runId,clientCode:deniedRun.ctx.client_code,path:'P3B'});const denySigned:any=await human.decide({authorization:'Bearer pipeline-human-token-0123456789','x-role':'human','x-actor':'@human:local'},deniedRun.runId,{approved:false,approval_id:denyPending.approval_id});const denyResult:any=await deniedRun.call('chatflows-p4','import',{runId:deniedRun.runId,clientCode:deniedRun.ctx.client_code,path:'P3B',approval:denySigned.approval});if(denyResult.status!=='ABORTED')throw new Error('DENY proof did not abort at P4 tool boundary');

 const tamperedFlow=await forceP3b(await build('acme_beauty_missing_kb'));await tamperedFlow.call('chatflows-p3b','generate',{triage:tamperedFlow.input,guidance:{}});await tamperedFlow.call('chatflows-p3b','selfcheck',{yaml:{}});const checkedFlow:any=(await store.latestArtifact(tamperedFlow.runId,'flow_yaml'))!.payload;await store.putArtifact(tamperedFlow.runId,'flow_yaml',{...checkedFlow,workflowYaml:checkedFlow.workflowYaml.replace('description: AgentTeams P3B generated flow','description: unreviewed but structurally valid mutation')},'flow-generate');const flowPending:any=await tamperedFlow.call('chatflows-p4','import',{runId:tamperedFlow.runId,clientCode:tamperedFlow.ctx.client_code,path:'P3B'}),flowSigned:any=await human.decide({authorization:'Bearer pipeline-human-token-0123456789','x-role':'human','x-actor':'@human:local'},tamperedFlow.runId,{approved:true,approval_id:flowPending.approval_id});const flowResponse:any=await mcp.rpc('chatflows-p4',{jsonrpc:'2.0',id:randomUUID(),method:'tools/call',params:{name:'import',arguments:{runId:tamperedFlow.runId,clientCode:tamperedFlow.ctx.client_code,path:'P3B',approval:flowSigned.approval,_ctx:tamperedFlow.ctx}}},auth);if(!flowResponse.error?.message.includes('selfcheck subject mismatch')||(await store.getRun(tamperedFlow.runId)).status!=='FAILED'||await store.latestArtifact(tamperedFlow.runId,'import_result'))throw new Error('tampered post-check FlowPackage reached P4 side effects');

 for(const [runId,path,status] of [[p3.runId,'P3','SUCCEEDED'],[p3b.runId,'P3B','SUCCEEDED'],[p3c.runId,'P3C',runtimeAvailable?'SUCCEEDED':'RUNNING']] as const){const run=await store.getRun(runId);if(run.build_path!==path||run.status!==status)throw new Error(path+' run state invalid');}
 if((await store.listArtifacts(p3c.runId,'expert_result')).length!==4)throw new Error('P3C expert artifacts missing');
 if((await store.findBlueprint(p3cimport.imported.external_id,p3c.ctx.client_code))?.status!=='PUBLISHED')throw new Error('P3C PUBLISHED record missing');
 if(!(await store.resolvePublished(p3c.ctx.client_code,runtimeSafeId('@human:local'),blueprint.runtimeAgentId)))throw new Error('P3C sandbox PUBLISHED binding missing');
 if(runtimeSafeId('@developer:local')!=='developer_local')throw new Error('runtimeSafeId drifted from sandbox chat');
 if(runtimeSafeId('@human:local')!=='human_local')throw new Error('approval actor runtimeSafeId drifted');
 if((await store.getRun(deniedRun.runId)).status!=='ABORTED'||await store.latestArtifact(deniedRun.runId,'import_result'))throw new Error('DENY left side effect or wrong state');
 const terminalReplay:any=await mcp.rpc('chatflows-p1',{jsonrpc:'2.0',id:randomUUID(),method:'tools/call',params:{name:'buildPhase1Result',arguments:{clientCode:p3.ctx.client_code,triage:p3.input,_ctx:p3.ctx}}},auth);if(!terminalReplay.error?.message.includes('P1 run is not active'))throw new Error('terminal run was replayed into P1');
 process.stdout.write('[PASS] Worker-only MCP routes P3/P3B/P3C, binds all selfcheck subjects, enforces Human approval, '+(runtimeAvailable?'completes all P4 dry-runs':'completes workflows and stages P3C')+'\n');await app.close();
}
main().then(()=>process.exit(0)).catch(error=>{process.stderr.write((error instanceof Error?error.stack:String(error))+'\n');process.exit(1);});
