import { randomUUID } from 'crypto'; import { Pool,PoolClient } from 'pg';
const url=process.env.DATABASE_URL?.trim(),runtimeUrl=process.env.AGENT_RUNTIME_DATABASE_URL?.trim();if(!url||!runtimeUrl)throw new Error('DATABASE_URL and AGENT_RUNTIME_DATABASE_URL required');
const ssl=process.env.DATABASE_SSL==='1'?{rejectUnauthorized:true}:undefined,pool=new Pool({connectionString:url,max:2,ssl}),runtimePool=new Pool({connectionString:runtimeUrl,max:1,ssl});
async function tx<T>(tenant:string,role:string|undefined,fn:(c:PoolClient)=>Promise<T>){const c=await pool.connect();try{await c.query('begin');await c.query("select set_config('app.client_code',$1,true)",[tenant]);if(role)await c.query('set local role '+role);const out=await fn(c);await c.query('commit');return out;}catch(e){await c.query('rollback');throw e;}finally{c.release();}}
async function mustReject(fn:()=>Promise<unknown>,message:string){try{await fn();}catch{return;}throw new Error(message);}
async function main(){
 const membership=await pool.query("select pg_has_role(current_user,'chatflows_app','member') as app");if(!membership.rows[0]?.app)throw new Error('DATABASE_URL login is not a member of chatflows_app');
 const tenant='contract_'+randomUUID().replace(/-/g,'').slice(0,12),other=tenant+'_other',run=randomUUID(),bp='bp_'+randomUUID().replace(/-/g,''),agent='agent_'+randomUUID().replace(/-/g,'');
 await tx(tenant,undefined,c=>c.query("insert into run(run_id,client_code,status,current_phase) values($1,$2,'RUNNING','P1')",[run,tenant]));
 await mustReject(()=>tx(tenant,'worker_p2',c=>c.query("insert into artifact(artifact_id,run_id,client_code,kind,version,payload,written_by) values($1,$2,$3,'triage',1,'{}','template-match')",[randomUUID(),run,tenant])),'worker_p2 wrote triage');
 await tx(tenant,'worker_p2',c=>c.query("insert into artifact(artifact_id,run_id,client_code,kind,version,payload,written_by) values($1,$2,$3,'match_result',1,'{}','template-match')",[randomUUID(),run,tenant]));
 await tx(tenant,'worker_p3c',c=>c.query("insert into artifact(artifact_id,run_id,client_code,kind,version,payload,written_by) values($1,$2,$3,'expert_result',1,'{}','persona-expert')",[randomUUID(),run,tenant]));
 await tx(tenant,'worker_p4',c=>c.query("insert into artifact(artifact_id,run_id,client_code,kind,version,payload,written_by) values($1,$2,$3,'approval',1,$4::jsonb,'flow-import-run')",[randomUUID(),run,tenant,JSON.stringify({approval_id:'a1',status:'PENDING'})]));
 const blueprint={blueprintId:bp,clientCode:tenant,runtimeAgentId:agent,version:1,runtime:{isolationScope:'USER'}};await tx(tenant,'worker_p3c',c=>c.query("insert into agent_blueprint(blueprint_id,client_code,runtime_agent_id,version,status,payload,source_run_id,written_by) values($1,$2,$3,1,'DRAFT',$4::jsonb,$5,'blueprint-compose')",[bp,tenant,agent,JSON.stringify(blueprint),run]));
 await tx(tenant,'worker_p4',c=>c.query("update agent_blueprint set status='STAGED' where blueprint_id=$1",[bp]));await mustReject(()=>tx(tenant,'worker_p4',c=>c.query("update agent_blueprint set status='PUBLISHED' where blueprint_id=$1",[bp])),'worker_p4 published Blueprint');
 await tx(tenant,'blueprint_admin',c=>c.query("update agent_blueprint set status='PUBLISHED' where blueprint_id=$1",[bp]));await tx(tenant,'worker_p4',c=>c.query("insert into agent_binding(client_code,user_id,runtime_agent_id,blueprint_id) values($1,'contract-user',$2,$3)",[tenant,agent,bp]));
 const hidden=await tx(other,undefined,c=>c.query('select count(*)::int as n from run where run_id=$1',[run]));if(hidden.rows[0].n!==0)throw new Error('cross-tenant run visible');
 const runtimeMembership=await runtimePool.query("select pg_has_role(current_user,'agent_runtime','member') as runtime,pg_has_role(current_user,'chatflows_app','member') as app");if(!runtimeMembership.rows[0]?.runtime||runtimeMembership.rows[0]?.app)throw new Error('runtime LOGIN role membership is not least privilege');
 const runtimeTx=async<T>(fn:(c:PoolClient)=>Promise<T>)=>{const c=await runtimePool.connect();try{await c.query('begin');await c.query("select set_config('app.client_code',$1,true)",[tenant]);const out=await fn(c);await c.query('commit');return out;}catch(e){await c.query('rollback');throw e;}finally{c.release();}};
 await mustReject(()=>runtimeTx(c=>c.query("update agent_blueprint set status='RETIRED' where blueprint_id=$1",[bp])),'agent_runtime mutated Blueprint');await runtimeTx(c=>c.query("update agent_binding set projected_version=1,projected_at=now() where client_code=$1 and runtime_agent_id=$2",[tenant,agent]));
 process.stdout.write('[PASS] PostgreSQL RLS, A7b roles, Blueprint transitions and runtime boundary\n');
}
main().finally(()=>Promise.all([pool.end(),runtimePool.end()])).then(()=>process.exit(0)).catch(error=>{process.stderr.write((error instanceof Error?error.message:String(error))+'\n');process.exit(1);});
