import 'reflect-metadata';
import { randomUUID } from 'crypto';
import { HttpException } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { AppMcpModule } from '../src/app-mcp.module';
import { ArtifactStoreService } from '../src/artifacts/artifact-store.service';
import { ApprovalProofService } from '../src/common/approval-proof.service';
import { ProductPhase } from '../src/common/product-phase';
import { PipelineController } from '../src/orchestration/pipeline.controller';
import { BlueprintAdminController } from '../src/artifacts/blueprint-admin.controller';

async function rejected(action:()=>Promise<unknown>|unknown,status:number){try{await action();}catch(error){return error instanceof HttpException&&error.getStatus()===status;}return false;}
async function pending(store:ArtifactStoreService,client:string){const runId=randomUUID();await store.ensureRun(runId,client);await store.updateRun(runId,{status:'WAITING_HUMAN',current_phase:ProductPhase.P4_IMPORT_RUN,build_path:'P3B'});const approvalId=randomUUID();await store.putArtifact(runId,'approval',{approval_id:approvalId,action:'P4_IMPORT',status:'PENDING'},'flow-import-run');return{runId,approvalId};}
async function main(){
 process.env.PIPELINE_CONTROL_TOKEN='pipeline-control-contract-token';process.env.PIPELINE_APPROVAL_SIGNING_SECRET='approval-signing-secret-at-least-32-characters';process.env.BLUEPRINT_ADMIN_TOKEN='blueprint-admin-contract-token';process.env.ORCHESTRATION_MODE='platform';
 const app=await NestFactory.createApplicationContext(AppMcpModule,{logger:false}),controller=app.get(PipelineController),blueprintAdmin=app.get(BlueprintAdminController),proofs=app.get(ApprovalProofService),store=app.get(ArtifactStoreService);await store.reset();
 if(!await rejected(()=>controller.createRun({}, {client_code:'acme'}),401))throw new Error('run issuer accepted no token');if(!await rejected(()=>controller.createRun({authorization:'Bearer pipeline-control-contract-token','x-role':'human','x-actor':'@reviewer:local'},{client_code:'acme'}),403))throw new Error('Human issued run');const issued:any=await controller.createRun({authorization:'Bearer pipeline-control-contract-token','x-role':'orchestrator','x-actor':'@manager:local'},{client_code:'acme'});if((await store.getRun(issued.run_id)).client_code!=='acme'||(await store.getRun(issued.run_id)).current_phase!=='P1')throw new Error('issued run was not persisted at P1');
 const triage={scene_id:'beauty_wecom_cs',agent_family:'customer_success',channel:'wecom',industry:'beauty',confidence:0.92,reason:'contract',known_slots:{industry:'beauty',role:'customer_success',desired_capabilities:['faq_retrieve','product_recommend','human_escalate']},missing_slots:[],ask_user:'',risk_flags:[]};
 const seeded:any=await controller.createRun({authorization:'Bearer pipeline-control-contract-token','x-role':'orchestrator','x-actor':'@manager:local'},{client_code:'acme',phase1_result:{phase:'P1',client_code:'acme',gate:'PASS',triage}});
 const seededRun=await store.getRun(seeded.run_id);if(seededRun.current_phase!=='P2'||!(await store.latestArtifact(seeded.run_id,'triage'))||!(await store.latestArtifact(seeded.run_id,'wizard_state')))throw new Error('PASS Phase1Result was not ingested into P2');
 if(!await rejected(()=>controller.createRun({authorization:'Bearer pipeline-control-contract-token','x-role':'orchestrator','x-actor':'@manager:local'},{client_code:'acme',phase1_result:{gate:'PASS',client_code:'other',triage}}),400))throw new Error('tenant-mismatched Phase1Result was ingested');
 if(!await rejected(()=>controller.start({authorization:'Bearer pipeline-control-contract-token','x-role':'orchestrator','x-actor':'@manager:local'},{client_code:'acme'}),409))throw new Error('platform mode executed local pipeline');
 const first=await pending(store,'acme');if(!await rejected(()=>controller.decide({},first.runId,{approved:true,approval_id:first.approvalId}),401))throw new Error('approval accepted no token');if(!await rejected(()=>controller.decide({authorization:'Bearer pipeline-control-contract-token','x-role':'orchestrator','x-actor':'manager'},first.runId,{approved:true,approval_id:first.approvalId}),403))throw new Error('orchestrator approved Human gate');
 const approved:any=await controller.decide({authorization:'Bearer pipeline-control-contract-token','x-role':'human','x-actor':'@reviewer:local'},first.runId,{approved:true,approval_id:first.approvalId});const decoded=proofs.verify(approved.approval.proof);if(decoded.run_id!==first.runId||decoded.actor!=='@reviewer:local')throw new Error('signed proof identity mismatch');
 const second=await pending(store,'acme');const denied:any=await controller.decide({authorization:'Bearer pipeline-control-contract-token','x-role':'human','x-actor':'@reviewer:local'},second.runId,{approved:false,approval_id:second.approvalId});const denyProof=proofs.verify(denied.approval.proof);if(denyProof.decision!=='DENY'||(await store.getRun(second.runId)).status!=='WAITING_HUMAN')throw new Error('DENY signer mutated business state or signed wrong decision');
 const race=await pending(store,'acme');const transitions=await Promise.allSettled([store.transitionApproval(race.runId,race.approvalId,'PENDING',{approval_id:race.approvalId,status:'PROCESSING'}),store.transitionApproval(race.runId,race.approvalId,'PENDING',{approval_id:race.approvalId,status:'PROCESSING'})]);if(transitions.filter(x=>x.status==='fulfilled').length!==1)throw new Error('approval compare-and-set is not atomic');
 process.env.ORCHESTRATION_MODE='local';const local:any=await controller.start({authorization:'Bearer pipeline-control-contract-token','x-role':'orchestrator','x-actor':'@developer:local'},{client_code:'acme_beauty',channel:'wecom',industry_id:'beauty',goal_ids:['faq_deflect','present_recommend'],business_brief:'本地控制契约测试'});if(local.status!=='WAITING_HUMAN'||!local.approval_id)throw new Error('local pipeline did not persist approval');const localDenied:any=await controller.decide({authorization:'Bearer pipeline-control-contract-token','x-role':'human','x-actor':'@reviewer:local'},local.run_id,{approved:false,approval_id:local.approval_id});if(localDenied.status!=='ABORTED'||(await store.getRun(local.run_id)).status!=='ABORTED')throw new Error('local approval did not execute PipelineService');process.env.ORCHESTRATION_MODE='platform';
 const bpRun=randomUUID();await store.ensureRun(bpRun,'acme');const bp:any={blueprintId:'bp-a',version:0,clientCode:'acme',runtimeAgentId:'agent-a',meta:{runId:bpRun},prompt:{agentsMd:'a',soulMd:'s',knowledgeMd:'k'},skills:[],tools:{allow:[],deny:[],mcpServers:[]},runtime:{model:'m',isolationScope:'USER',maxContextTokens:10},guidance:{role:'r',tone:'t',reply_length:'m',conditions:[],escalation_conditions:[]}};await store.persistBlueprint(bpRun,bp);bp.blueprintId='bp-b';bp.runtime.isolationScope='AGENT';let immutable=false;try{await store.persistBlueprint(bpRun,bp);}catch(error){immutable=error instanceof Error&&error.message.includes('isolationScope');}if(!immutable)throw new Error('A17 isolationScope mutation accepted');
 bp.blueprintId='bp-v1';bp.runtime.isolationScope='USER';const v1=await store.persistBlueprint(bpRun,bp);await store.stageBlueprint(v1.blueprint_id,'acme');if(!await rejected(()=>blueprintAdmin.publish({},v1.blueprint_id,'acme'),401))throw new Error('Blueprint publish accepted without admin token');await blueprintAdmin.publish({authorization:'Bearer blueprint-admin-contract-token','x-role':'admin','x-actor':'@publisher:local'},v1.blueprint_id,'acme');bp.blueprintId='bp-v2';bp.prompt.agentsMd='v2';const v2=await store.persistBlueprint(bpRun,bp);await store.stageBlueprint(v2.blueprint_id,'acme');await blueprintAdmin.publish({authorization:'Bearer blueprint-admin-contract-token','x-role':'admin','x-actor':'@publisher:local'},v2.blueprint_id,'acme');await blueprintAdmin.rollback({authorization:'Bearer blueprint-admin-contract-token','x-role':'admin','x-actor':'@rollback:local'},'acme','agent-a','1');const audits=(await store.listArtifacts(bpRun,'evidence')).map(a=>a.payload as any),publishAudits=audits.filter(a=>a.event==='BLUEPRINT_PUBLISHED'),rollbackAudits=audits.filter(a=>a.event==='BLUEPRINT_ROLLED_BACK');if(publishAudits.length!==2||rollbackAudits.length!==1||rollbackAudits[0].actor!=='@rollback:local'||rollbackAudits[0].version!==1)throw new Error('atomic Blueprint publish/rollback audit missing');
 process.stdout.write('[PASS] run issuer, platform/local split, Human RBAC, A17 and atomic publication audit\n');await app.close();
}
main().then(()=>process.exit(0)).catch(error=>{process.stderr.write((error instanceof Error?error.stack:String(error))+'\n');process.exit(1);});
