package com.yjiyun.chatflows.manager.agent;
import com.yjiyun.chatflows.manager.observability.ManagerTelemetry; import io.agentscope.core.ReActAgent; import io.agentscope.core.agent.RuntimeContext; import io.agentscope.core.event.*; import io.agentscope.core.message.*; import io.agentscope.core.model.Model; import io.agentscope.core.state.JsonFileAgentStateStore; import io.agentscope.core.tool.Toolkit; import io.agentscope.extensions.model.dashscope.DashScopeChatModel; import io.opentelemetry.api.trace.Span; import java.net.URI; import java.nio.file.Path; import java.util.*; import java.util.concurrent.atomic.AtomicInteger;
/** LLM only decides scheduling through four bounded tools; two failures open the deterministic fallback. */
public final class OrchestrationPlanner implements AutoCloseable {
 private static final String SOUL="You are a scheduling-only orchestrator. Never produce triage, catalog IDs, gates, YAML business artifacts or blueprints. For a new run use only this exact sequence: declare_team with the supplied fixed YAML, dispatch_phase once with phase P1, then call await_leader and stop while it is suspended. Never dispatch P2/P3/P4; the Team Leader owns those phases. When an await_leader result is supplied, acknowledge completion without calling any tool.";
 private final DeterministicPlanner fallback; private final OrchestrationTools tools; private final Config config; private final AtomicInteger failures=new AtomicInteger(); private final ReActAgent agent;
 public OrchestrationPlanner(DeterministicPlanner fallback,OrchestrationTools tools,Config config){this(fallback,tools,config,null);}
 OrchestrationPlanner(DeterministicPlanner fallback,OrchestrationTools tools,Config config,Model modelOverride){this.fallback=fallback;this.tools=tools;this.config=config;if(config.enabled()){validateGateway(config.baseUrl());Toolkit toolkit=new Toolkit();toolkit.registerTool(tools);Model model=modelOverride!=null?modelOverride:DashScopeChatModel.builder().apiKey(config.token()).baseUrl(config.baseUrl()).modelName(config.model().replaceFirst("^dashscope:","")).build();agent=ReActAgent.builder().name("orchestration-planner").sysPrompt(SOUL).model(model).toolkit(toolkit).stateStore(new JsonFileAgentStateStore(Path.of(config.stateHome()))).maxIters(6).build();}else agent=null;}
 public String mode(){return config.enabled()&&failures.get()<2?"llm":"deterministic";}
 public void start(OrchestrationRun run,String spec)throws Exception{String selected=mode();Span span=ManagerTelemetry.start("plan",run.runId(),run.clientCode(),"orchestration");ManagerTelemetry.planner(span,selected);String prompt="Schedule run_id="+run.runId()+" client_code="+run.clientCode()+" room_id="+run.roomId()+". Fixed Team YAML:\n"+config.teamYaml()+"\nP1 spec:\n"+spec;ManagerTelemetry.input(span,"user",prompt);try{if(!"llm".equals(selected)){fallback.start(run,spec);ManagerTelemetry.output(span,"assistant","deterministic planner: declared team + dispatched P1",selected);ManagerTelemetry.success(span);return;}try{Invocation invocation=invoke(List.of(new UserMessage(prompt)),context(run));ManagerTelemetry.usage(span,invocation.inputTokens(),invocation.outputTokens());Msg reply=invocation.reply();if(!tools.wasDispatched(run.runId()))throw new IllegalStateException("LLM planner returned without dispatch");ToolUseBlock waiting=reply==null?null:reply.getContentBlocks(ToolUseBlock.class).stream().filter(tool->"await_leader".equals(tool.getName())).findFirst().orElse(null);if(waiting==null)throw new IllegalStateException("LLM planner did not suspend at await_leader");run.suspended(waiting.getId());run.event("planned",Map.of("planner","llm"));failures.set(0);ManagerTelemetry.output(span,"assistant",summarize(reply),"tool_calls");ManagerTelemetry.success(span);}catch(Exception e){int count=failures.incrementAndGet();boolean dispatched=tools.wasDispatched(run.runId());run.planner("deterministic");run.event("planner_failed",Map.of("attempt",count,"fallback",!dispatched,"error",safe(e)));ManagerTelemetry.planner(span,"deterministic");if(!dispatched)fallback.start(run,spec);ManagerTelemetry.output(span,"assistant","llm planner failed ("+safe(e)+"); fell back to deterministic dispatch","deterministic");ManagerTelemetry.success(span);}}catch(Exception e){ManagerTelemetry.failure(span,e);throw e;}finally{ManagerTelemetry.end(span);}}
 public void resume(OrchestrationRun run,String leaderResult){if(agent==null)return;String toolId=run.beginResume();if(toolId==null)return;Span span=ManagerTelemetry.start("plan.resume",run.runId(),run.clientCode(),"orchestration");ManagerTelemetry.planner(span,"llm");ManagerTelemetry.input(span,"tool",leaderResult);try{Invocation invocation=invoke(List.of(new ToolResultMessage(toolId,"await_leader",leaderResult)),context(run));ManagerTelemetry.usage(span,invocation.inputTokens(),invocation.outputTokens());ManagerTelemetry.output(span,"assistant",summarize(invocation.reply()),"stop");run.resumed();ManagerTelemetry.success(span);}catch(Exception e){run.resumeFailed();run.event("planner_resume_failed",Map.of("error",safe(e)));ManagerTelemetry.failure(span,e);}finally{ManagerTelemetry.end(span);}}
 // reply 摘要：优先文本；无文本时列出工具调用名（planner 的 reply 通常只有 await_leader tool_use，无正文）。
 private static String summarize(Msg reply){if(reply==null)return "(no reply)";String text=reply.getTextContent();if(text!=null&&!text.isBlank())return text;List<ToolUseBlock> calls=reply.getContentBlocks(ToolUseBlock.class);if(calls.isEmpty())return "(no textual content)";StringBuilder b=new StringBuilder("tool_calls:");for(ToolUseBlock call:calls)b.append(' ').append(call.getName());return b.toString();}
 public void close(){if(agent!=null)agent.close();}
 public static void validateGateway(String raw){URI u=URI.create(raw);String host=u.getHost(),lower=host==null?"":host.toLowerCase();boolean privateHost=!lower.isBlank()&&(lower.equals("localhost")||lower.equals("127.0.0.1")||lower.equals("::1")||lower.startsWith("10.")||lower.startsWith("192.168.")||lower.matches("172\\.(1[6-9]|2\\d|3[01])\\..*")||!lower.contains("."));boolean secure="https".equalsIgnoreCase(u.getScheme())||("http".equalsIgnoreCase(u.getScheme())&&privateHost);if(!secure||(!privateHost&&!lower.contains("higress"))||u.getPath()==null||u.getPath().isBlank()||"/".equals(u.getPath()))throw new IllegalStateException("ORCHESTRATOR_LLM_BASE_URL must target a Higress route over HTTPS or private-network HTTP");}
 private static RuntimeContext context(OrchestrationRun run){return RuntimeContext.builder().userId("agent-manager").sessionId(run.runId()).put("run_id",run.runId()).put("client_code",run.clientCode()).build();}
 private Invocation invoke(List<Msg> messages,RuntimeContext context){List<AgentEvent> events=agent.streamEvents(messages,context).collectList().block();if(events==null)throw new IllegalStateException("AgentScope returned no events");int input=0,output=0;Msg reply=null;for(AgentEvent event:events){if(event instanceof ModelCallEndEvent end&&end.getUsage()!=null){input+=end.getUsage().getInputTokens();output+=end.getUsage().getOutputTokens();}else if(event instanceof AgentResultEvent result)reply=result.getResult();}if(reply==null)throw new IllegalStateException("AgentScope returned no result");return new Invocation(reply,input,output);}
 private static String safe(Exception e){String value=e.getMessage();return(value==null?e.getClass().getSimpleName():value).replaceAll("[\\r\\n]"," ").substring(0,Math.min(200,value==null?e.getClass().getSimpleName().length():value.length()));}
 private record Invocation(Msg reply,int inputTokens,int outputTokens){}
 public record Config(boolean enabled,String model,String baseUrl,String token,String teamYaml,String stateHome){public Config{if(enabled&&(baseUrl==null||baseUrl.isBlank()||token==null||token.length()<16||stateHome==null||stateHome.isBlank()))throw new IllegalStateException("LLM gateway URL/token/state home required");}}
}
