package com.yjiyun.chatflows.manager.agent;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.*; import com.yjiyun.chatflows.manager.control.RunIds; import java.nio.file.*; import java.time.Instant; import java.util.*; import java.util.concurrent.ConcurrentHashMap;
public final class OrchestrationStore {
 private static final ObjectMapper JSON=new ObjectMapper(); private final Map<String,OrchestrationRun> runs=new ConcurrentHashMap<>(); private final Path root;
 public OrchestrationStore(){root=null;} public OrchestrationStore(Path root){this.root=Objects.requireNonNull(root);try{Files.createDirectories(root);try(var files=Files.list(root)){files.filter(path->path.getFileName().toString().matches("[0-9a-fA-F-]{36}\\.json")).forEach(this::load);}}catch(Exception e){throw new IllegalStateException("cannot load orchestration state",e);}}
 public synchronized OrchestrationRun create(String runId,String clientCode,String roomId,String planner){RunIds.requireV4(runId);if(runs.containsKey(runId))throw new IllegalStateException("run already exists");OrchestrationRun run=new OrchestrationRun(runId,clientCode,roomId,planner,Instant.now(),"DISPATCHED","",null,List.of(),List.of(),Set.of(),this::persist);runs.put(runId,run);run.event("created",Map.of("planner",planner));return run;}
 public OrchestrationRun require(String runId){OrchestrationRun run=runs.get(RunIds.requireV4(runId));if(run==null)throw new NoSuchElementException("orchestration not found");return run;}
 private void persist(OrchestrationRun run){if(root==null)return;Path file=root.resolve(run.runId()+".json"),tmp=root.resolve(run.runId()+".json.tmp");try{Files.writeString(tmp,JSON.writeValueAsString(run.snapshot()),StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING);try{Files.move(tmp,file,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(AtomicMoveNotSupportedException e){Files.move(tmp,file,StandardCopyOption.REPLACE_EXISTING);}}catch(Exception e){throw new IllegalStateException("cannot persist orchestration "+run.runId(),e);}}
 private void load(Path file){try{JsonNode n=JSON.readTree(file.toFile());String id=RunIds.requireV4(text(n,"run_id")),client=text(n,"client_code"),room=text(n,"room_id"),planner=text(n,"planner"),status=text(n,"status"),summary=n.path("summary").asText(""),suspended=n.path("suspended_tool_id").isTextual()?n.path("suspended_tool_id").asText():null;List<OrchestrationRun.Event> events=new ArrayList<>();for(JsonNode e:n.path("events"))events.add(new OrchestrationRun.Event(e.path("id").asLong(),text(e,"type"),text(e,"at"),JSON.convertValue(e.path("data"),new TypeReference<Map<String,Object>>(){})));List<OrchestrationRun.ArtifactSummary> artifacts=new ArrayList<>();for(JsonNode a:n.path("artifacts"))artifacts.add(new OrchestrationRun.ArtifactSummary(text(a,"kind"),text(a,"state"),text(a,"at"),text(a,"detail")));Set<String> approvals=new LinkedHashSet<>();for(JsonNode a:n.path("pending_approvals"))approvals.add(a.asText());OrchestrationRun run=new OrchestrationRun(id,client,room,planner,Instant.parse(text(n,"created_at")),status,summary,suspended,events,artifacts,approvals,this::persist);if(runs.putIfAbsent(id,run)!=null)throw new IllegalStateException("duplicate persisted run: "+id);}catch(Exception e){throw new IllegalStateException("invalid orchestration state: "+file,e);}}
 private static String text(JsonNode n,String key){String value=n.path(key).asText("");if(value.isBlank())throw new IllegalStateException(key+" missing");return value;}
}
