package com.yjiyun.chatflows.manager.agent;
import com.yjiyun.chatflows.manager.control.RunIds; import java.time.Instant; import java.util.*; import java.util.concurrent.CopyOnWriteArrayList; import java.util.function.Consumer;
public final class OrchestrationRun {
 private final String runId,clientCode,roomId; private volatile String planner; private final Instant createdAt; private volatile String status,summary,suspendedToolId; private boolean resumeStarted; private final List<Event> events=new CopyOnWriteArrayList<>(); private final Map<String,ArtifactSummary> artifacts=new java.util.concurrent.ConcurrentHashMap<>(); private final Set<String> pendingApprovals=java.util.concurrent.ConcurrentHashMap.newKeySet(); private final Consumer<OrchestrationRun> persist;
 public OrchestrationRun(String runId,String clientCode,String roomId,String planner){this(runId,clientCode,roomId,planner,Instant.now(),"DISPATCHED","",null,List.of(),List.of(),Set.of(),run->{});event("created",Map.of("planner",planner));}
 OrchestrationRun(String runId,String clientCode,String roomId,String planner,Instant createdAt,String status,String summary,String suspendedToolId,List<Event> events,List<ArtifactSummary> artifacts,Set<String> approvals,Consumer<OrchestrationRun> persist){this.runId=RunIds.requireV4(runId);if(clientCode==null||!clientCode.matches("[A-Za-z0-9_-]+"))throw new IllegalArgumentException("invalid client_code");if(roomId==null||roomId.isBlank())throw new IllegalArgumentException("room_id required");this.clientCode=clientCode;this.roomId=roomId;this.planner=planner;this.createdAt=createdAt;this.status=status;this.summary=summary;this.suspendedToolId=suspendedToolId;this.events.addAll(events);for(ArtifactSummary artifact:artifacts)this.artifacts.put(artifact.kind(),artifact);this.pendingApprovals.addAll(approvals);this.persist=persist;}
 public void event(String type,Map<String,?> data){events.add(new Event(events.size()+1,type,Instant.now().toString(),Map.copyOf(data)));persist.accept(this);}
 public synchronized void terminal(String value,String text){if(status.equals(value)&&summary.equals(text))return;status=value;summary=text;event("done",Map.of("status",value));}
 public synchronized void abort(String actor,String reason){if(Set.of("SUCCEEDED","FAILED","ABORTED").contains(status))throw new IllegalStateException("run is already terminal: "+status);if(actor==null||actor.isBlank()||reason==null||reason.isBlank())throw new IllegalArgumentException("abort actor and reason required");status="ABORTED";summary=reason;pendingApprovals.clear();suspendedToolId=null;resumeStarted=false;event("aborted",Map.of("actor",actor,"reason",reason));event("done",Map.of("status","ABORTED"));}
 public void pendingApproval(String id){if(pendingApprovals.add(id))event("approval_required",Map.of("approval_id",id));}
 public void planner(String mode){planner=mode;persist.accept(this);}
 public synchronized void suspended(String toolId){if(toolId==null||toolId.isBlank())throw new IllegalArgumentException("tool id required");suspendedToolId=toolId;resumeStarted=false;event("planner_suspended",Map.of("tool","await_leader"));}
 public synchronized String beginResume(){if(suspendedToolId==null||resumeStarted)return null;resumeStarted=true;return suspendedToolId;}
 public synchronized void resumeFailed(){resumeStarted=false;} public synchronized void resumed(){suspendedToolId=null;resumeStarted=false;event("planner_resumed",Map.of("tool","await_leader"));}
 public void approval(String id,boolean approved,String actor){pendingApprovals.remove(id);event("approval",Map.of("approval_id",id,"approved",approved,"actor",actor));}
 public boolean artifact(String kind,String state,String detail){boolean added=artifacts.putIfAbsent(kind,new ArtifactSummary(kind,state,Instant.now().toString(),detail))==null;if(added)event("artifact",Map.of("kind",kind,"state",state));return added;}
 public Map<String,Object> view(){Map<String,Object> out=new LinkedHashMap<>();out.put("run_id",runId);out.put("client_code",clientCode);out.put("room_id",roomId);out.put("planner",planner);out.put("status",status);out.put("summary",summary);out.put("created_at",createdAt.toString());out.put("planner_waiting",suspendedToolId!=null);out.put("artifacts",List.copyOf(artifacts.values()));out.put("pending_approvals",List.copyOf(pendingApprovals));out.put("events",List.copyOf(events));return out;}
 public List<Event> events(){return List.copyOf(events);} public String runId(){return runId;} public String clientCode(){return clientCode;} public String roomId(){return roomId;} synchronized Map<String,Object> snapshot(){Map<String,Object> out=new LinkedHashMap<>(view());out.put("suspended_tool_id",suspendedToolId);return out;}
 public record Event(long id,String type,String at,Map<String,?> data){} public record ArtifactSummary(String kind,String state,String at,String detail){}
}
