package com.yjiyun.chatflows.manager.control;
import com.fasterxml.jackson.databind.*; import com.yjiyun.chatflows.manager.OrchestratorAgent; import com.yjiyun.chatflows.manager.artifact.TaskArtifactStore; import com.yjiyun.chatflows.manager.matrix.MatrixClient; import java.io.*; import java.util.*; import java.util.regex.*;
/** Resumable top-level task waiter. It routes no business phase and reads only control summaries. */
public final class RunSupervisor {
 private static final ObjectMapper JSON=new ObjectMapper(); private static final Pattern REQUEST=Pattern.compile("APPROVAL_REQUIRED\\s+run_id=([A-Za-z0-9_-]+)\\s+approval_id=([A-Za-z0-9_-]+)"),INFORMAL_APPROVAL=Pattern.compile("approval_id=([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})"),ARTIFACT=Pattern.compile("(?m)^(?:[-*]\\s*)?(?:artifact:\\s*)?([a-z][a-z0-9_]*)@(\\d+)\\s*$");
 private final OrchestratorAgent orchestrator; private final MatrixClient matrix; private final TaskArtifactStore tasks; private final ApprovalProofSigner signer; private final Set<String> humans,leaders,managers; private final String leaderId;
 public RunSupervisor(OrchestratorAgent o,MatrixClient m,TaskArtifactStore t,ApprovalProofSigner signer,Set<String> humans,Set<String> leaders,Set<String> managers){orchestrator=Objects.requireNonNull(o);matrix=Objects.requireNonNull(m);tasks=Objects.requireNonNull(t);this.signer=Objects.requireNonNull(signer);this.humans=Set.copyOf(humans);this.leaders=Set.copyOf(leaders);this.managers=Set.copyOf(managers);if(this.humans.isEmpty()||this.managers.isEmpty())throw new IllegalArgumentException("Human/Manager allowlists required");leaderId=com.yjiyun.chatflows.manager.ManagerComposition.onlyLeader(this.leaders);}
 public Result run(String room,String runId,String clientCode,String spec,boolean dispatch,long timeoutMillis,long pollMillis)throws Exception{validate(runId,clientCode);if(timeoutMillis<=0||pollMillis<0)throw new IllegalArgumentException("invalid supervisor timeout");matrix.join(room);if(dispatch)orchestrator.dispatch(room,runId,clientCode,"orchestration",spec);long deadline=System.currentTimeMillis()+timeoutMillis;Set<String> signed=new HashSet<>();while(System.currentTimeMillis()<deadline){String timeline=matrix.receive(room);signed.addAll(existingProofs(timeline,runId,managers));for(String approvalId:requests(timeline,runId,leaders))if(signed.add(approvalId)){try{ApprovalDecision decision=ApprovalTimeline.latest(timeline,runId,approvalId,humans);String proof=signer.sign(decision);matrix.sendMention(room,leaderId,"@chatflows-leader APPROVAL_PROOF run_id="+runId+" approval_id="+approvalId+" decision="+decision.decision()+" proof="+proof);}catch(IllegalStateException waitingForHuman){signed.remove(approvalId);}}Result result=terminal(tasks.readResultIfExists(runId).orElse(null),runId);if(result!=null){orchestrator.resultReceived(runId,clientCode);return result;}if(pollMillis>0)Thread.sleep(Math.min(pollMillis,Math.max(1,deadline-System.currentTimeMillis())));}throw new IllegalStateException("task timed out: "+runId);}
 public static Set<String> requests(String timeline,String runId,Set<String> leaders)throws IOException{Set<String> out=new LinkedHashSet<>();JsonNode root=JSON.readTree(timeline);for(JsonNode event:root.path("chunk")){if(!"m.room.message".equals(event.path("type").asText())||!"m.text".equals(event.path("content").path("msgtype").asText())||!leaders.contains(event.path("sender").asText()))continue;String body=event.path("content").path("body").asText();Matcher m=REQUEST.matcher(body);while(m.find()){if(sameRun(runId,m.group(1)))out.add(m.group(2));}if(RunIds.mentionedIn(body,runId)&&(body.contains("等待 Human 审批")||body.contains("WAITING_HUMAN")||body.contains("pending_approval")||body.contains("APPROVAL_REQUIRED"))){Matcher informal=INFORMAL_APPROVAL.matcher(body);if(informal.find())out.add(informal.group(1));}}return out;}
 private static boolean sameRun(String runId,String mentioned){return runId.equals(mentioned)||runId.startsWith(mentioned)||(mentioned.length()>=8&&runId.startsWith(mentioned.substring(0,8)));}
 static Set<String> existingProofs(String timeline,String runId,Set<String> managers)throws IOException{Set<String> out=new HashSet<>();JsonNode root=JSON.readTree(timeline);Pattern p=Pattern.compile("^@chatflows-leader APPROVAL_PROOF run_id="+Pattern.quote(runId)+" approval_id=([A-Za-z0-9_-]+)\\s+decision=(?:APPROVE|DENY)\\s+proof=.+$");for(JsonNode event:root.path("chunk")){if(!managers.contains(event.path("sender").asText()))continue;Matcher m=p.matcher(event.path("content").path("body").asText().trim());if(m.matches())out.add(m.group(1));}return out;}
 public static Result terminal(String body,String runId){if(body==null)return null;String normalized=body.replace("\r\n","\n");if(!normalized.startsWith("---\n"))return null;int end=normalized.indexOf("\n---\n",4);if(end<0)return null;Map<String,String> fields=new HashMap<>();for(String line:normalized.substring(4,end).split("\n")){int colon=line.indexOf(':');if(colon<1)return null;String key=line.substring(0,colon).trim(),value=line.substring(colon+1).trim();if(fields.putIfAbsent(key,value)!=null)return null;}String status=fields.get("status");if(!runId.equals(fields.get("run_id"))||status==null||!Set.of("SUCCEEDED","ABORTED","FAILED").contains(status))return null;return new Result(runId,status,body);}
 private static void validate(String runId,String client){RunIds.requireV4(runId);if(client==null||!client.matches("[A-Za-z0-9_-]+"))throw new IllegalArgumentException("invalid client id");}
 public static List<ArtifactPointer> artifacts(String body){if(body==null)return List.of();List<ArtifactPointer> out=new ArrayList<>();Matcher matcher=ARTIFACT.matcher(body);while(matcher.find())out.add(new ArtifactPointer(matcher.group(1),Integer.parseInt(matcher.group(2))));return List.copyOf(out);}
 public record Result(String runId,String status,String summary){} public record ArtifactPointer(String kind,int version){}
}
