package com.yjiyun.chatflows.runtime.api;
import com.yjiyun.chatflows.runtime.agent.RuntimeContextFactory; import com.yjiyun.chatflows.runtime.blueprint.*; import com.yjiyun.chatflows.runtime.observability.*; import com.yjiyun.chatflows.runtime.security.TenantToolPermissions; import io.agentscope.core.agent.RuntimeContext; import io.agentscope.core.event.AgentEvent; import io.agentscope.core.skill.SkillFilter; import io.agentscope.harness.agent.HarnessAgent; import reactor.core.publisher.Flux;
public final class RuntimeService { private final HarnessAgent agent; private final BlueprintProjector projector; private final TenantToolPermissions permissions; private final RuntimeContextFactory contexts=new RuntimeContextFactory(); public RuntimeService(HarnessAgent a,BlueprintProjector p,TenantToolPermissions permissions){agent=a;projector=p;this.permissions=permissions;}
 public String chat(String client,String user,String session,String runtimeAgent,String message){RuntimeContext rc=contexts.create(client,user,session,runtimeAgent);AgentBlueprint bp=projector.projectPublished(client,user,runtimeAgent,rc);prepare(rc,bp);return agent.call(message,rc).block().getTextContent();}
 public Flux<AgentEvent> stream(String client,String user,String session,String runtimeAgent,String message){RuntimeContext rc=contexts.create(client,user,session,runtimeAgent);AgentBlueprint bp=projector.projectPublished(client,user,runtimeAgent,rc);prepare(rc,bp);return agent.streamEvents(message,rc);}
 public boolean dryRun(String client,String user,String runtimeAgent){String out=chat(client,user,"dryrun-"+System.nanoTime(),runtimeAgent,"health check");return out!=null&&!out.isBlank();}
 public String dryRun(AgentBlueprint bp,String user){RuntimeContext rc=contexts.create(bp.clientCode(),user,"dryrun-"+System.nanoTime(),bp.runtimeAgentId());projector.projectEphemeral(bp,rc);prepare(rc,bp);String out=agent.call("health check",rc).block().getTextContent();if(out==null||out.isBlank())throw new IllegalStateException("empty dry-run response");return out;}
 private void prepare(RuntimeContext rc,AgentBlueprint bp){permissions.install(agent,rc,bp.clientCode());String[] names=bp.skills().stream().map(AgentBlueprint.Skill::name).toArray(String[]::new);rc.put(SkillFilter.class,SkillFilter.only(names));rc.put(BlueprintTraceMiddleware.CONTEXT_KEY,OtelAttributes.forCall(bp));}
}
