package com.yjiyun.chatflows.runtime;
import com.fasterxml.jackson.databind.*; import com.yjiyun.chatflows.runtime.agent.*; import com.yjiyun.chatflows.runtime.api.RuntimeService; import com.yjiyun.chatflows.runtime.blueprint.*; import com.yjiyun.chatflows.runtime.observability.OtelAttributes; import com.yjiyun.chatflows.runtime.security.TenantToolPermissions; import java.nio.file.*; import java.util.*;
public final class CrossLanguageSelfTest {
 public static void main(String[] args)throws Exception{
  if(args.length!=1)throw new IllegalArgumentException("Blueprint JSON path required");ObjectMapper json=new ObjectMapper();JsonNode n=json.readTree(Files.readString(Path.of(args[0])));AgentBlueprint bp=convert(n);
  Path ws=Files.createTempDirectory("cross-runtime");System.setProperty("agentscope.state.home",ws.resolve("state").toString());Files.writeString(ws.resolve("AGENTS.md"),"seed");Files.writeString(ws.resolve("SOUL.md"),"seed");Files.writeString(ws.resolve("tools.json"),"{\"mcpServers\":{}}");
  try(AgentFactory factory=new AgentFactory(ws,new DeterministicModel())){InMemoryBlueprintRepository repo=new InMemoryBlueprintRepository();repo.stage(bp,"node-p3c");repo.publish(bp.blueprintId(),bp.clientCode(),"human-reviewer");TenantToolPermissions permissions=new TenantToolPermissions();BlueprintProjector projector=new BlueprintProjector(factory.agent(),repo,permissions);RuntimeService runtime=new RuntimeService(factory.agent(),projector,permissions);String answer=runtime.chat(bp.clientCode(),"cross-user","cross-session",bp.runtimeAgentId(),"跨语言健康检查");if(!answer.contains("DRY_RUN_OK"))throw new AssertionError(answer);var rc=new RuntimeContextFactory().create(bp.clientCode(),"cross-user","verify",bp.runtimeAgentId());projector.projectPublished(bp.clientCode(),"cross-user",bp.runtimeAgentId(),rc);String agents=factory.agent().getWorkspaceManager().readAgentsMd(rc);if(!agents.equals(bp.prompt().agentsMd()))throw new AssertionError("Node prompt was not projected verbatim");Map<String,String> attrs=OtelAttributes.forCall(bp);if(bp.meta()==null||bp.meta().runId()==null||!bp.meta().runId().equals(attrs.get("agentteams.run_id"))||!attrs.keySet().containsAll(Set.of("agentteams.client_code","agentteams.runtime_agent_id","agentteams.blueprint_id","agentteams.blueprint_version","agentteams.run_id")))throw new AssertionError("Blueprint provenance lost: "+attrs);System.out.println("[PASS] Node P3C Blueprint -> Java publish -> USER projection -> HarnessAgent chat + OTel provenance");}
 }
 private static AgentBlueprint convert(JsonNode n){List<AgentBlueprint.Skill> skills=new ArrayList<>();for(JsonNode s:n.path("skills"))skills.add(new AgentBlueprint.Skill(s.path("name").asText(),s.path("source").asText(),text(s,"ref"),text(s,"skillMd")));List<String> allow=new ArrayList<>(),deny=new ArrayList<>();n.path("tools").path("allow").forEach(x->allow.add(x.asText()));n.path("tools").path("deny").forEach(x->deny.add(x.asText()));List<AgentBlueprint.McpServer> servers=new ArrayList<>();for(JsonNode s:n.path("tools").path("mcpServers"))servers.add(new AgentBlueprint.McpServer(s.path("name").asText(),s.path("url").asText(),s.path("transport").asText()));List<String> scenarios=new ArrayList<>();n.path("meta").path("scenarios").forEach(x->scenarios.add(x.asText()));AgentBlueprint.Meta meta=new AgentBlueprint.Meta(text(n.path("meta"),"industry"),scenarios,text(n.path("meta"),"generatedBy"),text(n.path("meta"),"runId"));return new AgentBlueprint(n.path("blueprintId").asText(),n.path("version").asInt(),n.path("clientCode").asText(),n.path("runtimeAgentId").asText(),meta,new AgentBlueprint.Prompt(n.path("prompt").path("agentsMd").asText(),n.path("prompt").path("soulMd").asText(),text(n.path("prompt"),"knowledgeMd")),skills,new AgentBlueprint.Tools(allow,deny,servers),new AgentBlueprint.RuntimeSpec(n.path("runtime").path("model").asText(),n.path("runtime").path("isolationScope").asText(),n.path("runtime").path("maxContextTokens").asInt()));}
 private static String text(JsonNode n,String key){JsonNode v=n.get(key);return v==null||v.isNull()?null:v.asText();}
}
