package com.yjiyun.chatflows.runtime;
import com.yjiyun.chatflows.runtime.agent.*; import com.yjiyun.chatflows.runtime.api.RuntimeService; import com.yjiyun.chatflows.runtime.blueprint.*; import com.yjiyun.chatflows.runtime.security.TenantToolPermissions; import java.nio.file.*; import java.util.*; import java.util.concurrent.*;
/** Cross-language P3C P4 smoke: one generated Blueprint per installed industry scene. */
public final class IndustrySmokeSelfTest {
 public static void main(String[] args)throws Exception{
  if(args.length!=1)throw new IllegalArgumentException("Blueprint smoke directory required");Path dir=Path.of(args[0]);Set<String> expected=Set.of("beauty","agriculture","edu","recruiting"),seen=new HashSet<>();Path ws=Files.createTempDirectory("industry-smoke");System.setProperty("agentscope.state.home",ws.resolve("state").toString());Files.writeString(ws.resolve("AGENTS.md"),"seed");Files.writeString(ws.resolve("SOUL.md"),"seed");Files.writeString(ws.resolve("tools.json"),"{\"mcpServers\":{}}");
  try(AgentFactory factory=new AgentFactory(ws,new DeterministicModel())){InMemoryBlueprintRepository repo=new InMemoryBlueprintRepository();TenantToolPermissions permissions=new TenantToolPermissions();BlueprintProjector projector=new BlueprintProjector(factory.agent(),repo,permissions);RuntimeService runtime=new RuntimeService(factory.agent(),projector,permissions);
   for(String industry:expected){System.out.println("[SMOKE] "+industry+" start");System.out.flush();Path file=dir.resolve(industry+".json");if(!Files.isRegularFile(file))throw new AssertionError("missing smoke: "+file);AgentBlueprint bp=BlueprintJson.read(file);if(bp.meta()==null||!industry.equals(bp.meta().industry())||!"USER".equals(bp.runtime().isolationScope()))throw new AssertionError("invalid "+industry+" Blueprint");String response;try{response=CompletableFuture.supplyAsync(()->runtime.dryRun(bp,"user-"+industry)).get(30,TimeUnit.SECONDS);}catch(TimeoutException e){throw new AssertionError(industry+" dry-run exceeded 30s",e);}if(!response.contains("DRY_RUN_OK"))throw new AssertionError(industry+": "+response);if("beauty".equals(industry)){String repeat;try{repeat=CompletableFuture.supplyAsync(()->runtime.dryRun(bp,"user-"+industry)).get(30,TimeUnit.SECONDS);}catch(TimeoutException e){throw new AssertionError("beauty repeat dry-run exceeded 30s",e);}if(!repeat.contains("DRY_RUN_OK"))throw new AssertionError("beauty repeat dry-run: "+repeat);}seen.add(industry);System.out.println("[SMOKE] "+industry+" done");System.out.flush();}
  }
  if(!seen.equals(expected))throw new AssertionError(seen);System.out.println("[PASS] Java P4 assembled and dry-ran Node-generated Blueprints for beauty/agriculture/edu/recruiting");
 }
}
