package com.yjiyun.chatflows.runtime;
import com.yjiyun.chatflows.runtime.agent.*; import com.yjiyun.chatflows.runtime.api.RuntimeService; import com.yjiyun.chatflows.runtime.blueprint.*; import com.yjiyun.chatflows.runtime.security.TenantToolPermissions; import com.yjiyun.chatflows.runtime.skill.*; import io.agentscope.core.agent.RuntimeContext; import io.agentscope.core.message.*; import io.agentscope.core.model.*; import io.agentscope.core.state.*; import io.agentscope.harness.agent.DistributedStore; import io.agentscope.harness.agent.filesystem.remote.store.InMemoryStore; import java.nio.file.*; import java.util.*; import reactor.core.publisher.Flux;
public final class RuntimeDistributedSelfTest {
 public static void main(String[] args)throws Exception{
  Path ws=Files.createTempDirectory("runtime-distributed");Files.writeString(ws.resolve("AGENTS.md"),"seed");Files.writeString(ws.resolve("SOUL.md"),"seed");Files.writeString(ws.resolve("tools.json"),"{\"mcpServers\":{}}");
  InMemoryStore files=new InMemoryStore();SharedStateStore states=new SharedStateStore();DistributedStore shared=DistributedStore.builder().baseStore(files).agentStateStore(states).build();
  CapturingModel model1=new CapturingModel(),model2=new CapturingModel();ReadOnlySkillRepository market=new ReadOnlySkillRepository("market",List.of(ReadOnlySkillRepository.skill("shared-help","MARKET-VERSION")));
  try(AgentFactory first=AgentFactory.distributed(ws,model1,shared,market);AgentFactory second=AgentFactory.distributed(ws,model2,shared,market)){
   InMemoryBlueprintRepository repo=new InMemoryBlueprintRepository();AgentBlueprint bp=blueprint();repo.stage(bp,"builder");repo.publish(bp.blueprintId(),bp.clientCode(),"admin");TenantToolPermissions permissions1=new TenantToolPermissions(),permissions2=new TenantToolPermissions();BlueprintProjector projector1=new BlueprintProjector(first.agent(),repo,permissions1),projector2=new BlueprintProjector(second.agent(),repo,permissions2);RuntimeService runtime1=new RuntimeService(first.agent(),projector1,permissions1),runtime2=new RuntimeService(second.agent(),projector2,permissions2);
   String one=runtime1.chat("tenant-v6","alice","same-session","agent-v6","first-turn");if(!one.contains("OK"))throw new AssertionError(one);
   String prompt=model1.allSystems();if(!prompt.contains("TENANT-INLINE-VERSION")||prompt.contains("MARKET-VERSION"))throw new AssertionError("Layer4 did not override Layer2: "+prompt);
   RuntimeContext rc=new RuntimeContextFactory().create("tenant-v6","alice","same-session","agent-v6");String projected=second.agent().getWorkspaceManager().readAgentsMd(rc);if(!projected.contains("tenant-v6-style"))throw new AssertionError("second replica cannot read remote workspace");
   if(projector2.projectedVersion("tenant-v6","alice","agent-v6")!=1)throw new AssertionError("projected_version not shared across replicas");
   runtime2.chat("tenant-v6","alice","same-session","agent-v6","second-turn");String history=model2.allText();if(!history.contains("first-turn")||!history.contains("second-turn"))throw new AssertionError("second replica cannot resume state: "+history);
   AgentBlueprint libraryV2=new AgentBlueprint("bp-v6-lib",2,"tenant-v6","agent-v6",bp.meta(),bp.prompt(),List.of(new AgentBlueprint.Skill("shared-help","library","skill:shared-help@2",null)),bp.tools(),bp.runtime());repo.stage(libraryV2,"builder");repo.publish(libraryV2.blueprintId(),libraryV2.clientCode(),"admin");int beforeSwitch=model2.callCount();runtime2.chat("tenant-v6","alice","next-session","agent-v6","library-version");String switched=model2.systemsSince(beforeSwitch);if(!switched.contains("MARKET-VERSION")||switched.contains("TENANT-INLINE-VERSION"))throw new AssertionError("stale Layer4 Skill survived library switch: "+switched);if(second.agent().getWorkspaceManager().getFilesystem().exists(rc,"skills/shared-help/SKILL.md"))throw new AssertionError("stale inline Skill file not deleted");
   RuntimeContext bob=new RuntimeContextFactory().create("tenant-v6","bob","other","agent-v6");if(second.agent().getWorkspaceManager().readAgentsMd(bob).contains("tenant-v6-style"))throw new AssertionError("USER isolation leaked remote workspace");
  }
  System.out.println("[PASS] V6 Layer4>Layer2 and two RemoteFilesystem replicas share workspace/session without tenant leakage");
 }
 private static AgentBlueprint blueprint(){return new AgentBlueprint("bp-v6",1,"tenant-v6","agent-v6",new AgentBlueprint.Meta("test",List.of("v6"),"test","run-v6"),new AgentBlueprint.Prompt("# tenant-v6-style","# soul","# knowledge"),List.of(new AgentBlueprint.Skill("shared-help","inline",null,"---\nname: shared-help\ndescription: TENANT-INLINE-VERSION\n---\nuse tenant version")),new AgentBlueprint.Tools(List.of("read_file","memory_search","load_skill_through_path"),List.of(),List.of()),new AgentBlueprint.RuntimeSpec("capture","USER",8000));}
 private static final class CapturingModel implements Model {private final List<List<Msg>> calls=Collections.synchronizedList(new ArrayList<>());public Flux<ChatResponse> stream(List<Msg> msgs,List<ToolSchema> tools,GenerateOptions options){calls.add(List.copyOf(msgs));return Flux.just(ChatResponse.builder().content(List.of(TextBlock.builder().text("OK").build())).usage(new ChatUsage(1,1,0)).finishReason("stop").build());}public String getModelName(){return "capture";}public int getContextWindowSize(){return 32768;}int callCount(){return calls.size();}String allSystems(){return systemsSince(0);}String systemsSince(int start){synchronized(calls){return calls.subList(Math.min(start,calls.size()),calls.size()).stream().flatMap(List::stream).filter(m->m.getRole()==MsgRole.SYSTEM).map(Msg::getTextContent).reduce("",(a,b)->a+"\n"+b);}}String allText(){return calls.stream().flatMap(List::stream).map(Msg::getTextContent).reduce("",(a,b)->a+"\n"+b);}}
 private static final class SharedStateStore implements AgentStateStore {private final InMemoryAgentStateStore delegate=new InMemoryAgentStateStore();public void save(String u,String s,String k,State v){delegate.save(u,s,k,v);}public void save(String u,String s,String k,List<? extends State> v){delegate.save(u,s,k,v);}public <T extends State> Optional<T> get(String u,String s,String k,Class<T> t){return delegate.get(u,s,k,t);}public <T extends State> List<T> getList(String u,String s,String k,Class<T> t){return delegate.getList(u,s,k,t);}public boolean exists(String u,String s){return delegate.exists(u,s);}public void delete(String u,String s){delegate.delete(u,s);}public void delete(String u,String s,String k){delegate.delete(u,s,k);}public Set<String> listSessionIds(String u){return delegate.listSessionIds(u);}}
}
