package com.yjiyun.chatflows.manager;
import java.net.URI; import java.nio.file.*; import java.util.*;
public record ManagerConfig(String controllerUrl,String controllerToken,String matrixUrl,String matrixToken,String matrixUserId,String matrixPassword,String taskFsEndpoint,String taskFsAccessKey,String taskFsSecretKey,String taskFsBucket,String taskFsPrefix,String approvalSigningSecret,Set<String> humanIds,Set<String> leaderIds,Set<String> managerIds,String managerAuthToken,String managerAdminToken,String managerHost,int managerPort,String nestControlUrl,String pipelineControlToken,String leaderRoomId,boolean orchestratorLlm,String orchestratorModel,String orchestratorBaseUrl,String orchestratorToken,String orchestratorStateHome,String teamYaml){
 public static ManagerConfig from(Map<String,String> env,boolean serve){String user=opt(env,"AGENTTEAMS_MATRIX_USER_ID"),token=opt(env,"AGENTTEAMS_MATRIX_ACCESS_TOKEN"),password=opt(env,"AGENTTEAMS_MATRIX_PASSWORD");if(token==null&&(user==null||password==null))throw new IllegalStateException("Matrix access token or user/password required");Set<String> managers=parseIds(req(env,"AGENTTEAMS_MANAGER_IDS"));if(user!=null&&!managers.contains(user))throw new IllegalStateException("AGENTTEAMS_MATRIX_USER_ID must be in AGENTTEAMS_MANAGER_IDS");String llmBase=env.getOrDefault("ORCHESTRATOR_LLM_BASE_URL",""),llmToken=env.getOrDefault("HIGRESS_CONSUMER_TOKEN","");if(serve&&env.getOrDefault("DASHSCOPE_API_KEY","").length()>0)throw new IllegalStateException("agent-manager must not receive DASHSCOPE_API_KEY; use Higress consumer credentials");String llmMode=env.getOrDefault("ORCHESTRATOR_LLM","off");if(!"on".equalsIgnoreCase(llmMode)&&!"off".equalsIgnoreCase(llmMode))throw new IllegalStateException("ORCHESTRATOR_LLM must be on or off");boolean llm=serve&&"on".equalsIgnoreCase(llmMode);if(llm){com.yjiyun.chatflows.manager.agent.OrchestrationPlanner.validateGateway(llmBase);if(llmToken.length()<16)throw new IllegalStateException("HIGRESS_CONSUMER_TOKEN must contain at least 16 characters when ORCHESTRATOR_LLM=on");}String team=readTeam(env.getOrDefault("AGENTTEAMS_TEAM_FILE","../agentteams-resources/team.yaml"));return new ManagerConfig(req(env,"AGENTTEAMS_CONTROLLER_URL"),req(env,"AGENTTEAMS_AUTH_TOKEN"),req(env,"AGENTTEAMS_MATRIX_URL"),token,user,password,req(env,"CHATFLOWS_TASK_FS_ENDPOINT"),req(env,"CHATFLOWS_TASK_FS_ACCESS_KEY"),req(env,"CHATFLOWS_TASK_FS_SECRET_KEY"),req(env,"CHATFLOWS_TASK_FS_BUCKET"),req(env,"CHATFLOWS_TASK_FS_PREFIX"),req(env,"CHATFLOWS_APPROVAL_SIGNING_SECRET"),parseIds(req(env,"AGENTTEAMS_HUMAN_IDS")),parseIds(req(env,"AGENTTEAMS_LEADER_IDS")),managers,serve?req(env,"MANAGER_AUTH_TOKEN"):env.getOrDefault("MANAGER_AUTH_TOKEN","unused-cli-token"),serve?req(env,"MANAGER_ADMIN_TOKEN"):env.getOrDefault("MANAGER_ADMIN_TOKEN","unused-admin-token"),env.getOrDefault("MANAGER_HOST","127.0.0.1"),Integer.parseInt(env.getOrDefault("MANAGER_PORT","8090")),serve?req(env,"CHATFLOWS_NEST_URL"):env.getOrDefault("CHATFLOWS_NEST_URL","http://127.0.0.1:3100"),serve?req(env,"PIPELINE_CONTROL_TOKEN"):env.getOrDefault("PIPELINE_CONTROL_TOKEN","unused-control-token"),env.getOrDefault("AGENTTEAMS_LEADER_ROOM_ID",""),llm,env.getOrDefault("ORCHESTRATOR_MODEL","dashscope:qwen-plus"),llmBase,llmToken,env.getOrDefault("ORCHESTRATOR_STATE_HOME","./data/orchestrator-state"),team);}
 private static String readTeam(String path){try{return Files.readString(Path.of(path));}catch(Exception e){throw new IllegalStateException("cannot read AGENTTEAMS_TEAM_FILE: "+path,e);}}
 private static String opt(Map<String,String> env,String key){String value=env.get(key);return value==null||value.isBlank()?null:value;}
 private static Set<String> parseIds(String raw){Set<String> out=new LinkedHashSet<>();for(String item:raw.split(",")){String id=item.trim();if(!id.matches("@[A-Za-z0-9._=-]+:[A-Za-z0-9.-]+(?::[0-9]{1,5})?"))throw new IllegalStateException("invalid Matrix user id: "+id);out.add(id);}if(out.isEmpty())throw new IllegalStateException("Matrix user allowlist required");return Set.copyOf(out);}
 private static String req(Map<String,String> env,String key){String value=env.get(key);if(value==null||value.isBlank())throw new IllegalStateException(key+" is required");return value;}
}
