package com.yjiyun.chatflows.manager;
import com.yjiyun.chatflows.manager.control.*; import com.yjiyun.chatflows.manager.platform.PlatformClient; import java.nio.file.*; import java.util.*;
import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;
/** Explicit production composition root; no local-file fallback and no default credentials. */
public final class ManagerApplication {
 public static void main(String[] args)throws Exception{
  com.yjiyun.chatflows.manager.observability.ManagerTelemetry.install(System.getenv()); // OTLP 引导（otlp+on 时注册全局 SDK，并置 otlpMode 停用 ROA 镜像）
  boolean serve=args.length>0&&"serve".equals(args[0]);ManagerConfig c=ManagerConfig.from(System.getenv(),serve);ManagerComposition composition=new ManagerComposition(c);if(serve){composition.checkHttp();ManagerServer server=new ManagerServer(composition);Runtime.getRuntime().addShutdownHook(new Thread(()->{server.close();composition.close();}));server.start();System.err.println("agent-manager listening on "+c.managerHost()+":"+server.port()+" planner="+composition.planner().mode());return;}composition.check();var tasks=composition.tasks();var matrix=composition.matrix();OrchestratorAgent manager=composition.orchestrator();String leaderId=ManagerComposition.onlyLeader(c.leaderIds());
  if(args.length==0||"check".equals(args[0])){System.out.println("[READY] AgentTeams controller/Matrix configured and MinIO bucket exists");return;}
  if("apply-manifest".equals(args[0])&&args.length==2){applyManifest(composition.platform(),Path.of(args[1]));return;}
  if("dispatch".equals(args[0])&&args.length==6){String spec=Files.readString(Path.of(args[5]));var carrier=manager.dispatch(args[1],args[2],args[3],args[4],spec);System.out.println(carrier.metaJson(args[4]));return;}
  if("collect".equals(args[0])&&args.length==4){System.out.println(manager.collect(args[1],args[2],args[3]));return;}
  if(("run".equals(args[0])&&args.length==5)||("resume".equals(args[0])&&args.length==4)){boolean first="run".equals(args[0]);String room=args[1],runId=args[2],client=args[3],spec=first?Files.readString(Path.of(args[4])):"";long timeout=Long.parseLong(System.getenv().getOrDefault("AGENTTEAMS_RUN_TIMEOUT_SECONDS","3600"))*1000L;RunSupervisor.Result result=new RunSupervisor(manager,matrix,tasks,new ApprovalProofSigner(c.approvalSigningSecret()),c.humanIds(),c.leaderIds(),c.managerIds()).run(room,runId,client,spec,first,timeout,2000);System.out.println("[TERMINAL] run_id="+result.runId()+" status="+result.status());return;}
  if("run-env".equals(args[0])&&args.length==1){String room=envRequired("AGENTTEAMS_LEADER_ROOM_ID"),client=envRequired("AGENTTEAMS_RUN_CLIENT_CODE"),runId=envOr("AGENTTEAMS_RUN_ID",UUID.randomUUID().toString()),resume=envOr("AGENTTEAMS_RESUME","0");boolean first=!"1".equals(resume);String spec=first?Files.readString(Path.of(envOr("AGENTTEAMS_RUN_SPEC","/specs/e2e-spec.md"))):"";long timeout=Long.parseLong(envOr("AGENTTEAMS_RUN_TIMEOUT_SECONDS","3600"))*1000L;RunSupervisor.Result result=new RunSupervisor(manager,matrix,tasks,new ApprovalProofSigner(c.approvalSigningSecret()),c.humanIds(),c.leaderIds(),c.managerIds()).run(room,runId,client,spec,first,timeout,2000);System.out.println("[TERMINAL] run_id="+result.runId()+" status="+result.status());requireExpectedStatus(result.status(),envOr("AGENTTEAMS_EXPECT_STATUS","SUCCEEDED"));return;}
  if("approval".equals(args[0])&&args.length==4){matrix.join(args[1]);ApprovalDecision decision=ApprovalTimeline.latest(matrix.receive(args[1]),args[2],args[3],c.humanIds());String proof=new ApprovalProofSigner(c.approvalSigningSecret()).sign(decision);String message="@chatflows-leader APPROVAL_PROOF run_id="+decision.runId()+" approval_id="+decision.approvalId()+" decision="+decision.decision()+" proof="+proof;matrix.sendMention(args[1],leaderId,message);System.out.println("[SIGNED] run_id="+decision.runId()+" approval_id="+decision.approvalId()+" decision="+decision.decision()+" proof=<redacted>");return;}
  throw new IllegalArgumentException("usage: check | apply-manifest <manifest.json> | run-env | run <roomId> <runId> <clientCode> <specFile> | resume <roomId> <runId> <clientCode> | dispatch ... | collect ... | approval ...");
 }
 static void applyManifest(PlatformClient platform,Path manifest)throws Exception{ObjectMapper json=new ObjectMapper();YAMLMapper yaml=new YAMLMapper();JsonNode root=json.readTree(Files.readString(manifest));if(root.path("version").asInt()!=1||!root.path("files").isArray())throw new IllegalArgumentException("render manifest invalid");Path dir=manifest.toAbsolutePath().getParent();for(JsonNode item:root.path("files")){String file=item.asText();if(!file.matches("[0-9]{3}-[a-z0-9-]+\\.yaml"))throw new IllegalArgumentException("rendered resource name invalid: "+file);Path resource=dir.resolve(file).normalize();if(!resource.getParent().equals(dir))throw new IllegalArgumentException("resource path traversal");String body=Files.readString(resource);JsonNode cr=yaml.readTree(body);String kind=cr.path("kind").asText(),name=cr.path("metadata").path("name").asText();platform.apply(kind,name,body);System.out.println("[APPLIED] "+kind+" "+name);}}
 private static String envRequired(String key){String value=System.getenv(key);if(value==null||value.isBlank())throw new IllegalStateException(key+" is required");return value;}
 static String envOr(Map<String,String> env,String key,String fallback){String value=env.get(key);return value==null||value.isBlank()?fallback:value;}
 static void requireExpectedStatus(String actual,String expected){if(!expected.equals(actual))throw new IllegalStateException("terminal status mismatch: expected="+expected+" actual="+actual);}
 private static String envOr(String key,String fallback){return envOr(System.getenv(),key,fallback);}
}
