package com.yjiyun.chatflows.manager;
import com.yjiyun.chatflows.manager.agent.*; import com.yjiyun.chatflows.manager.artifact.*; import com.yjiyun.chatflows.manager.control.*; import com.yjiyun.chatflows.manager.matrix.*; import com.yjiyun.chatflows.manager.platform.*; import java.net.URI; import java.nio.file.Path;
public final class ManagerComposition implements AutoCloseable {
 private final ManagerConfig config; private final MinioTaskArtifactStore tasks; private final RestPlatformClient platform; private final RestMatrixClient matrix; private final PipelineControlClient pipeline; private final OrchestratorAgent orchestrator; private final OrchestrationStore runs; private final OrchestrationPlanner planner;
 public ManagerComposition(ManagerConfig c)throws Exception{config=c;runs=new OrchestrationStore(Path.of(c.orchestratorStateHome(),"runs"));tasks=new MinioTaskArtifactStore(c.taskFsEndpoint(),c.taskFsAccessKey(),c.taskFsSecretKey(),c.taskFsBucket(),c.taskFsPrefix());platform=new RestPlatformClient(URI.create(c.controllerUrl()),c.controllerToken());MatrixTokenProvider tokens=new MatrixTokenProvider(c.matrixToken(),URI.create(c.controllerUrl()),c.controllerToken(),URI.create(c.matrixUrl()),c.matrixUserId(),c.matrixPassword());tokens.initialize();matrix=new RestMatrixClient(URI.create(c.matrixUrl()),tokens,c.matrixUserId(),c.matrixInviteUserId(),c.matrixInvitePassword());pipeline=new PipelineControlClient(URI.create(c.nestControlUrl()),c.pipelineControlToken());orchestrator=new OrchestratorAgent(platform,matrix,tasks,onlyLeader(c.leaderIds()));DeterministicPlanner deterministic=new DeterministicPlanner(orchestrator,c.teamYaml());planner=new OrchestrationPlanner(deterministic,new OrchestrationTools(orchestrator,matrix,c.teamYaml()),new OrchestrationPlanner.Config(c.orchestratorLlm(),c.orchestratorModel(),c.orchestratorBaseUrl(),c.orchestratorToken(),c.teamYaml(),c.orchestratorStateHome()));}
 public void check()throws Exception{tasks.checkAccess();platform.check();String identity=matrix.whoAmI();if(!config.managerIds().contains(identity))throw new IllegalStateException("Matrix token identity is not an authorized manager");}
 public void checkHttp()throws Exception{check();pipeline.check();}
 public ManagerConfig config(){return config;} public MinioTaskArtifactStore tasks(){return tasks;} public RestPlatformClient platform(){return platform;} public RestMatrixClient matrix(){return matrix;} public PipelineControlClient pipeline(){return pipeline;} public OrchestratorAgent orchestrator(){return orchestrator;} public OrchestrationStore runs(){return runs;} public OrchestrationPlanner planner(){return planner;} public void close(){planner.close();}
 public static String onlyLeader(java.util.Set<String> leaders){if(leaders==null||leaders.size()!=1)throw new IllegalArgumentException("exactly one Leader Matrix user id required");return leaders.iterator().next();}
}
