package com.yjiyun.chatflows.manager;
import com.yjiyun.chatflows.manager.artifact.TaskArtifactStore; import com.yjiyun.chatflows.manager.matrix.MatrixClient; import com.yjiyun.chatflows.manager.platform.PlatformClient; import com.yjiyun.chatflows.manager.observability.*; import io.agentscope.core.agent.RuntimeContext; import io.opentelemetry.api.trace.Span; import java.io.IOException; import java.util.Set; import java.util.concurrent.ConcurrentHashMap;
public final class OrchestratorAgent {
 private final PlatformClient platform; private final MatrixClient matrix; private final TaskArtifactStore tasks; private final AgentLoopExporter agentLoop; private final String leaderId; private final Set<String> dispatched=ConcurrentHashMap.newKeySet();
 public OrchestratorAgent(PlatformClient p,MatrixClient m,TaskArtifactStore t){this(p,m,t,"@chatflows-leader:localhost",new AgentLoopExporter(System.getenv()));} public OrchestratorAgent(PlatformClient p,MatrixClient m,TaskArtifactStore t,String leaderId){this(p,m,t,leaderId,new AgentLoopExporter(System.getenv()));} public OrchestratorAgent(PlatformClient p,MatrixClient m,TaskArtifactStore t,AgentLoopExporter exporter){this(p,m,t,"@chatflows-leader:localhost",exporter);} public OrchestratorAgent(PlatformClient p,MatrixClient m,TaskArtifactStore t,String leaderId,AgentLoopExporter exporter){platform=p;matrix=m;tasks=t;this.leaderId=requireLeaderId(leaderId);agentLoop=exporter;}
 public RuntimeContext context(String userId,String runId){return RuntimeContext.builder().userId(userId).sessionId(runId).put("run_id",runId).build();} public void apply(String kind,String name,String yaml)throws IOException,InterruptedException{platform.apply(kind,name,yaml);}
 public TraceCarrier dispatch(String roomId,String runId,String clientCode,String phase,String spec)throws IOException,InterruptedException{if(!dispatched.add(runId))throw new IllegalStateException("run already dispatched");Span span=ManagerTelemetry.start("dispatch",runId,clientCode,phase);try{TraceCarrier c=TraceCarrier.fromSpan(runId,clientCode,span);tasks.writeMeta(runId,c.metaJson(phase));tasks.writeSpec(runId,c.frontMatter(phase)+spec);String taskPath="shared/tasks/task-"+runId+"/";matrix.join(roomId);matrix.sendMention(roomId,leaderId,"@chatflows-leader NEW_RUN run_id="+runId+". Before any routing, call TeamHarness filesync exactly once with action=pull path="+taskPath+", then read "+taskPath+"spec.md and require its frontmatter run_id="+runId+". If pull/read/validation fails, report RUN_BLOCKED for this run; never use history or create a spec. _ctx={run_id:"+runId+",traceparent:"+c.traceparent()+"}");agentLoop.emit("agentteams.task",c,phase,"chatflows-leader",taskPath);agentLoop.emit("orchestrator.dispatch",c,phase,"chatflows-leader",taskPath);ManagerTelemetry.success(span);return c;}catch(IOException|InterruptedException|RuntimeException e){dispatched.remove(runId);ManagerTelemetry.failure(span,e);throw e;}finally{ManagerTelemetry.end(span);}}
 public boolean wasDispatched(String runId){return dispatched.contains(runId);} public TraceCarrier dispatch(String roomId,String runId,String clientCode,String spec)throws IOException,InterruptedException{return dispatch(roomId,runId,clientCode,"orchestration",spec);} public void dispatch(String roomId,String runId,String spec)throws IOException,InterruptedException{dispatch(roomId,runId,"unknown","orchestration",spec);}
 public String collect(String roomId,String runId,String clientCode)throws IOException,InterruptedException{Span span=ManagerTelemetry.start("collect",runId,clientCode,"orchestration");try{matrix.join(roomId);matrix.receive(roomId);String result=tasks.readResult(runId);resultReceived(runId,clientCode);ManagerTelemetry.success(span);return result;}catch(IOException|InterruptedException|RuntimeException e){ManagerTelemetry.failure(span,e);throw e;}finally{ManagerTelemetry.end(span);}}
 public void resultReceived(String runId,String clientCode)throws IOException{String spec=tasks.readSpec(runId);java.util.regex.Matcher m=java.util.regex.Pattern.compile("(?m)^traceparent:\\s*(00-[0-9a-f]{32}-[0-9a-f]{16}-0[01])\\s*$").matcher(spec);if(!m.find())throw new IOException("spec traceparent missing");agentLoop.emit("orchestrator.result_received",new TraceCarrier(runId,clientCode,m.group(1)),"orchestration","chatflows-leader","shared/tasks/task-"+runId+"/");} public String collect(String roomId,String runId)throws IOException,InterruptedException{return collect(roomId,runId,"unknown");}
 public static String requireLeaderId(String leaderId){if(leaderId==null||!leaderId.matches("@[A-Za-z0-9._=-]+:[A-Za-z0-9.-]+(?::[0-9]{1,5})?"))throw new IllegalArgumentException("full Leader Matrix user id required");return leaderId;}
}
