package com.yjiyun.chatflows.runtime.skill;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import io.agentscope.core.skill.AgentSkill; import io.agentscope.core.skill.repository.*; import io.agentscope.core.skill.util.SkillUtil; import java.sql.*; import java.util.*;
/** PostgreSQL-backed Layer-2 marketplace. Every transaction is read-only and assumes agent_runtime. */
public final class JdbcSkillRepository implements AgentSkillRepository {
 private final String url,user,password; private final ObjectMapper json=new ObjectMapper();
 public JdbcSkillRepository(String url,String user,String password){this.url=Objects.requireNonNull(url);this.user=user;this.password=password;}
 public AgentSkill getSkill(String name){return all("where name=? order by version desc limit 1",List.of(name)).stream().findFirst().orElse(null);}
 public List<String> getAllSkillNames(){List<String> out=new ArrayList<>();for(AgentSkill s:getAllSkills())out.add(s.getName());return out;}
 public List<AgentSkill> getAllSkills(){return all("where active=true order by name,version desc",List.of());}
 private List<AgentSkill> all(String suffix,List<Object> params){String sql="select distinct on (name) name,skill_md,resources from agentscope_skills "+suffix;try(Connection c=DriverManager.getConnection(url,user,password)){c.setReadOnly(true);c.setAutoCommit(false);try(Statement role=c.createStatement()){role.execute("set local role agent_runtime");}try(PreparedStatement q=c.prepareStatement(sql)){for(int i=0;i<params.size();i++)q.setObject(i+1,params.get(i));List<AgentSkill> out=new ArrayList<>();try(ResultSet rs=q.executeQuery()){while(rs.next()){Map<String,String> resources=rs.getString(3)==null?Map.of():json.readValue(rs.getString(3),new TypeReference<Map<String,String>>(){});out.add(SkillUtil.createFrom(rs.getString(2),resources,"postgres-market"));}}c.commit();return out;}catch(Exception e){c.rollback();throw e;}}catch(Exception e){throw new IllegalStateException("skill market read failed",e);}}
 public boolean save(List<AgentSkill>s,boolean f){throw new UnsupportedOperationException("read-only skill repository");}public boolean delete(String n){throw new UnsupportedOperationException("read-only skill repository");}public boolean skillExists(String n){return getSkill(n)!=null;}public AgentSkillRepositoryInfo getRepositoryInfo(){return new AgentSkillRepositoryInfo("postgres","agentscope_skills",false);}public String getSource(){return "postgres-market";}public void setWriteable(boolean w){if(w)throw new UnsupportedOperationException("read-only skill repository");}public boolean isWriteable(){return false;}
}
