package com.yjiyun.chatflows.manager;
import com.sun.net.httpserver.*; import com.yjiyun.chatflows.manager.agent.*; import com.yjiyun.chatflows.manager.api.*; import com.yjiyun.chatflows.manager.artifact.*; import com.yjiyun.chatflows.manager.control.*; import com.yjiyun.chatflows.manager.matrix.*; import com.yjiyun.chatflows.manager.platform.*; import com.yjiyun.chatflows.manager.security.AuthService; import java.io.*; import java.net.*; import java.net.http.*; import java.nio.file.*; import java.util.*; import java.util.concurrent.*;
public final class ManagerHttpSelfTest {
 private static final String TOKEN="manager-http-token-0123456789",ADMIN="manager-admin-token-0123456789",CONTROL="pipeline-control-token-0123456789",RUN="550e8400-e29b-41d4-a716-446655440000";
 public static void main(String[] args)throws Exception{
  HttpServer nest=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);nest.createContext("/api/v1/pipeline",x->{try{String path=x.getRequestURI().getPath();if(path.endsWith("/runs")){reply(x,200,"{\"run_id\":\""+RUN+"\",\"client_code\":\"acme\"}");}else if(path.endsWith("/approval")){reply(x,200,"{\"status\":\"SIGNED\",\"approval\":{\"approval_id\":\"a1\",\"actor\":\"@human:local\",\"decision\":\"APPROVE\",\"proof\":\"signed-proof\"}}");}else if(path.endsWith("/abort")){reply(x,200,"{\"run_id\":\""+RUN+"\",\"status\":\"ABORTED\"}");}else reply(x,200,"{\"ok\":true}");}catch(Exception e){throw new RuntimeException(e);}});nest.start();
  List<String> calls=new ArrayList<>();PlatformClient platform=(k,n,y)->calls.add("apply:"+k+":"+n);String timeline="{\"chunk\":[{\"type\":\"m.room.message\",\"event_id\":\"$new\",\"sender\":\"@leader:local\",\"origin_server_ts\":200,\"content\":{\"msgtype\":\"m.text\",\"body\":\"NEW_RUN run_id="+RUN+"\"}},{\"type\":\"m.room.member\",\"sender\":\"@leader:local\"},{\"type\":\"m.room.message\",\"event_id\":\"$old\",\"sender\":\"@persona-expert:local\",\"origin_server_ts\":100,\"content\":{\"msgtype\":\"m.text\",\"body\":\"ack\"}}]}";MatrixClient matrix=new MatrixClient(){public void join(String r){calls.add("join:"+r);}public void send(String r,String m){calls.add("send:"+m);}public String receive(String r){return timeline;}};Path root=Files.createTempDirectory("manager-http");OrchestratorAgent orchestrator=new OrchestratorAgent(platform,matrix,new FileTaskArtifactStore(root));String team="apiVersion: agentteams.io/v1beta1\nkind: Team\nmetadata: {name: chatflows-build-team}\nspec: {leader: chatflows-leader, workers: [wizard-intent]}";DeterministicPlanner deterministic=new DeterministicPlanner(orchestrator,team);OrchestrationPlanner planner=new OrchestrationPlanner(deterministic,new OrchestrationTools(orchestrator,matrix,team),new OrchestrationPlanner.Config(false,"dashscope:qwen-plus","","",team,root.resolve("state").toString()));OrchestrationStore store=new OrchestrationStore();PipelineControlClient pipeline=new PipelineControlClient(URI.create("http://127.0.0.1:"+nest.getAddress().getPort()),CONTROL);AuthService auth=new AuthService(TOKEN,ADMIN);
  HttpServer manager=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);manager.createContext("/api/v1/orchestrations",new OrchestrationController(auth,pipeline,store,planner,new FileTaskArtifactStore(root),matrix,Set.of("@leader:local"),Set.of("@human:local"),"!leader:local"));manager.createContext("/api/v1/health",new HealthController(()->calls.add("health:all-planes"),auth));ExecutorService executor=Executors.newCachedThreadPool();manager.setExecutor(executor);manager.start();URI base=URI.create("http://127.0.0.1:"+manager.getAddress().getPort());
  try {
   if(send(base,"GET","/api/v1/health",null,null,"user","viewer").statusCode()!=401)throw new AssertionError("anonymous health accepted");HttpResponse<String> health=send(base,"GET","/api/v1/health",null,TOKEN,"user","viewer");if(health.statusCode()!=200||!health.body().contains("nest-control")||!calls.contains("health:all-planes"))throw new AssertionError("authenticated health did not check all planes: "+health.body());
   if(send(base,"POST","/api/v1/orchestrations","{}",null,"orchestrator","actor").statusCode()!=401)throw new AssertionError("missing token accepted");if(send(base,"POST","/api/v1/orchestrations","{}",TOKEN,"human","actor").statusCode()!=403)throw new AssertionError("wrong create role accepted");if(send(base,"POST","/api/v1/orchestrations","{}",TOKEN,"admin","actor").statusCode()!=401)throw new AssertionError("regular token escalated via admin role");
   String create="{\"client_code\":\"acme\",\"spec\":\"build it\"}";HttpResponse<String> created=send(base,"POST","/api/v1/orchestrations",create,TOKEN,"orchestrator","manager");if(created.statusCode()!=202||!created.body().contains(RUN)||!calls.contains("apply:Team:chatflows-build-team"))throw new AssertionError("create failed: "+created.body()+" "+calls);
   HttpResponse<String> get=send(base,"GET","/api/v1/orchestrations/"+RUN,null,TOKEN,"user","viewer");if(get.statusCode()!=200||!get.body().contains("dispatch"))throw new AssertionError("get failed");if(send(base,"GET","/api/v1/orchestrations/"+RUN+"/room",null,null,"user","viewer").statusCode()!=401)throw new AssertionError("anonymous room accepted");HttpResponse<String> room=send(base,"GET","/api/v1/orchestrations/"+RUN+"/room",null,TOKEN,"user","viewer");if(room.statusCode()!=200||!room.body().contains("NEW_RUN")||!room.body().contains("\"for_run\":true")||!room.body().contains("!leader:local")||room.body().contains("m.room.member")||room.body().indexOf("ack")>room.body().indexOf("NEW_RUN")||!calls.contains("join:!leader:local"))throw new AssertionError("room failed: "+room.body()+" "+calls);HttpResponse<String> events=send(base,"GET","/api/v1/orchestrations/"+RUN+"/events?once=1",null,TOKEN,"user","viewer");if(events.statusCode()!=200||!events.body().contains("event: dispatch"))throw new AssertionError("SSE failed: "+events.body());
   if(send(base,"POST","/api/v1/orchestrations/"+RUN+"/approval","{\"approval_id\":\"a1\",\"approved\":true}",TOKEN,"human","").statusCode()!=400)throw new AssertionError("missing actor accepted");if(send(base,"POST","/api/v1/orchestrations/"+RUN+"/approval","{\"approval_id\":\"a1\",\"approved\":true}",TOKEN,"human","@intruder:local").statusCode()!=403)throw new AssertionError("non-Human actor accepted");if(send(base,"POST","/api/v1/orchestrations/"+RUN+"/approval","{\"approval_id\":\"a1\",\"approved\":true}",TOKEN,"human","@human:local").statusCode()!=200)throw new AssertionError("approval failed");if(calls.stream().noneMatch(value->value.contains("APPROVAL_PROOF run_id="+RUN)&&value.contains("proof=signed-proof")))throw new AssertionError("signed proof was not relayed to Leader");
   if(send(base,"POST","/api/v1/orchestrations/"+RUN+"/abort","{\"reason\":\"test cleanup\"}",TOKEN,"admin","admin").statusCode()!=401)throw new AssertionError("regular token used for admin abort");HttpResponse<String> aborted=send(base,"POST","/api/v1/orchestrations/"+RUN+"/abort","{\"reason\":\"test cleanup\"}",ADMIN,"admin","admin");if(aborted.statusCode()!=200||!aborted.body().contains("ABORTED")||calls.stream().noneMatch(value->value.contains("RUN_ABORTED run_id="+RUN)))throw new AssertionError("admin abort failed: "+aborted.body());
   System.out.println("[PASS] manager HTTP enforces auth/RBAC/actor and serves health, create, read, room, SSE, approval, admin abort");
  } finally {
   manager.stop(0);nest.stop(0);executor.shutdownNow();planner.close();
  }
 }
 private static HttpResponse<String> send(URI base,String method,String path,String body,String token,String role,String actor)throws Exception{HttpRequest.Builder b=HttpRequest.newBuilder(base.resolve(path));if(token!=null)b.header("Authorization","Bearer "+token);if(role!=null)b.header("X-Role",role);if(actor!=null&&!actor.isEmpty())b.header("X-Actor",actor);if(body==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(body));return HttpClient.newHttpClient().send(b.build(),HttpResponse.BodyHandlers.ofString());}
 private static void reply(HttpExchange x,int code,String body)throws IOException{byte[] bytes=body.getBytes();x.getResponseHeaders().set("Content-Type","application/json");x.sendResponseHeaders(code,bytes.length);try(OutputStream out=x.getResponseBody()){out.write(bytes);}}
}
