package com.yjiyun.chatflows.manager;
import com.yjiyun.chatflows.manager.artifact.*; import com.yjiyun.chatflows.manager.control.*; import com.yjiyun.chatflows.manager.matrix.*; import com.yjiyun.chatflows.manager.platform.*; import java.nio.file.*; import java.util.*;
public final class ManagerSelfTest {
 public static void main(String[] args)throws Exception{
  List<String> events=new ArrayList<>();MatrixClient matrix=new MatrixClient(){public void join(String r){events.add("join:"+r);}public void send(String r,String x){events.add("send:"+x);}public void sendMention(String r,String user,String x){events.add("mention:"+user+":"+x);}public String receive(String r){events.add("receive");return "ok";}public String sync(String since,long timeout){events.add("sync:"+timeout);return "{}";}};
  Path root=Files.createTempDirectory("manager-test");FileTaskArtifactStore tasks=new FileTaskArtifactStore(root);String leader="@chatflows-leader:matrix-local.agentteams.io:18080";OrchestratorAgent orchestrator=new OrchestratorAgent((k,n,y)->events.add("apply:"+k+":"+n),matrix,tasks,leader);String run="550e8400-e29b-41d4-a716-446655440000";
  orchestrator.apply("Worker","wizard-intent","yaml");var carrier=orchestrator.dispatch("room",run,"acme","P1","# spec");Path task=root.resolve("shared/tasks/task-"+run);String meta=Files.readString(task.resolve("meta.json")),spec=Files.readString(task.resolve("spec.md"));if(!meta.contains(carrier.traceparent())||!meta.contains("\"phase\":\"P1\"")||!spec.contains("phase: P1"))throw new AssertionError("trace/phase carrier lost");
  Files.writeString(task.resolve("result.md"),"done");if(!"done".equals(orchestrator.collect("room",run,"acme")))throw new AssertionError();matrix.sync(null,30000);if(!run.equals(orchestrator.context("user",run).getSessionId()))throw new AssertionError("sessionId != runId");String prefix="teams/chatflows-build-team/shared/tasks";if(!MinioTaskArtifactStore.key(prefix,run,"spec.md").equals(prefix+"/task-"+run+"/spec.md"))throw new AssertionError("MinIO key mismatch");boolean badPrefix=false;try{MinioTaskArtifactStore.key("agentteams/agentteams-storage/"+prefix,run,"spec.md");}catch(IllegalArgumentException expected){badPrefix=true;}if(!badPrefix)throw new AssertionError("mc alias/bucket root was accepted as part of the object key");
  String taskPath="shared/tasks/task-"+run+"/";if(events.stream().noneMatch(value->value.startsWith("mention:"+leader+":@chatflows-leader NEW_RUN run_id="+run)&&value.contains("action=pull path="+taskPath)&&value.contains("禁止复用历史 run 或自行创建 spec")&&value.contains("留在本 Team Room")&&value.contains("create_task_room")))throw new AssertionError("dispatch did not require an explicit validated FileSync pull: "+events);
  if(PipelineControlClient.phase1FromSpec("build it")!=null||PipelineControlClient.phase1FromSpec("{\"phase\":\"P1\"}")!=null||PipelineControlClient.phase1FromSpec("{\"phase1_result\":{\"gate\":\"ASK\"}}")!=null)throw new AssertionError("non-PASS spec was treated as ingested P1");
  if(!"PASS".equals(PipelineControlClient.phase1FromSpec("{\"phase\":\"P1\",\"phase1_result\":{\"gate\":\"PASS\",\"client_code\":\"acme\"}}").path("gate").asText()))throw new AssertionError("PASS Phase1Result was not extracted from wizard spec");
  String cr="apiVersion: agentteams.io/v1beta1\nkind: Worker\nmetadata: {name: wizard-intent}\nspec: {model: qwen3.6-plus, runtime: qwenpaw, skills: []}";if(!"wizard-intent".equals(RestPlatformClient.requestBody("Worker","wizard-intent",cr).path("name").asText()))throw new AssertionError("Worker CR conversion failed");
  String team="apiVersion: agentteams.io/v1beta1\nkind: Team\nmetadata: {name: chatflows-build-team}\nspec: {leader: chatflows-leader, workers: [wizard-intent]}";var teamBody=RestPlatformClient.requestBody("Team","chatflows-build-team",team);if(teamBody.path("workerMembers").size()!=2||!"team_leader".equals(teamBody.path("workerMembers").get(0).path("role").asText())||teamBody.has("workers")||teamBody.has("leader"))throw new AssertionError("Team CR conversion failed: "+teamBody);
  String human="apiVersion: agentteams.io/v1beta1\nkind: Human\nmetadata: {name: chatflows-coordinator}\nspec: {description: approver, permissionLevel: 2, accessibleTeams: [chatflows-build-team]}";var humanBody=RestPlatformClient.requestBody("Human","chatflows-coordinator",human);if(!"chatflows-coordinator".equals(humanBody.path("name").asText())||humanBody.path("permissionLevel").asInt()!=2||humanBody.path("accessibleTeams").size()!=1)throw new AssertionError("Human CR conversion failed");
  String approval="approval-1",timeline="{\"chunk\":[{\"type\":\"m.room.message\",\"sender\":\"@intruder:local\",\"content\":{\"msgtype\":\"m.text\",\"body\":\"APPROVE run_id="+run+" approval_id="+approval+"\"}},{\"type\":\"m.room.message\",\"sender\":\"@admin:local\",\"content\":{\"msgtype\":\"m.text\",\"body\":\"APPROVE run_id="+run+" approval_id="+approval+"\"}}]}";ApprovalDecision decision=ApprovalTimeline.latest(timeline,run,approval,Set.of("@admin:local"));if(!decision.approved()||!"@admin:local".equals(decision.actor())||new ApprovalProofSigner("approval-signing-secret-at-least-32-characters").sign(decision).split("\\.").length!=2)throw new AssertionError("approval contract failed");
  boolean proseRejected=false;try{ApprovalTimeline.latest(timeline.replace("APPROVE run_id="+run,"please APPROVE run_id="+run),run,approval,Set.of("@admin:local"));}catch(IllegalStateException e){proseRejected=true;}if(!proseRejected)throw new AssertionError("ambiguous approval accepted");
  boolean intruderRejected=false;try{ApprovalTimeline.latest(timeline,run,approval,Set.of("@nobody:local"));}catch(IllegalStateException e){intruderRejected=true;}if(!intruderRejected)throw new AssertionError("unauthorized Human accepted");
  if(Collections.frequency(events,"join:room")!=2||!events.contains("sync:30000"))throw new AssertionError("Matrix join/sync missing: "+events);System.out.println("[PASS] REST, Matrix HITL/HMAC, MinIO, OTel and UUID v4 run context");
 }
}
