package com.yjiyun.chatflows.runtime.blueprint;
import java.sql.*; import java.util.*;
/** Production repository: transaction is read-only and SET LOCAL ROLE agent_runtime. */
public final class JdbcBlueprintRepository implements BlueprintRepository {
 private final String url,user,password;
 public JdbcBlueprintRepository(String url,String user,String password){this.url=Objects.requireNonNull(url);this.user=user;this.password=password;}
 public boolean isReady(){try(Connection c=DriverManager.getConnection(url,user,password)){c.setReadOnly(true);c.setAutoCommit(false);try(Statement role=c.createStatement()){role.execute("set local role agent_runtime");}try(Statement q=c.createStatement();ResultSet rs=q.executeQuery("select to_regclass('public.agent_blueprint') is not null and to_regclass('public.agent_binding') is not null and to_regclass('public.agentscope_skills') is not null")){boolean ready=rs.next()&&rs.getBoolean(1);c.commit();return ready;}}catch(Exception e){return false;}}
 public Optional<AgentBlueprint> resolvePublished(String client,String userId,String agent){
  String sql="select b.payload from agent_binding a join agent_blueprint b on b.blueprint_id=a.blueprint_id where a.client_code=? and a.user_id=? and a.runtime_agent_id=? and b.status='PUBLISHED'";
  try(Connection c=DriverManager.getConnection(url,user,password)){c.setReadOnly(true);c.setAutoCommit(false);try(PreparedStatement set=c.prepareStatement("select set_config('app.client_code',?,true)")){set.setString(1,client);set.execute();}try(Statement role=c.createStatement()){role.execute("set local role agent_runtime");}try(PreparedStatement q=c.prepareStatement(sql)){q.setString(1,client);q.setString(2,userId);q.setString(3,agent);try(ResultSet rs=q.executeQuery()){Optional<AgentBlueprint> out=rs.next()?Optional.of(BlueprintJson.read(rs.getString(1))):Optional.empty();c.commit();return out;}}catch(Exception e){c.rollback();throw e;}}
 catch(Exception e){throw new IllegalStateException("PUBLISHED blueprint read failed",e);}
 }
 public int projectedVersion(String client,String userId,String agent){String sql="select projected_version from agent_binding where client_code=? and user_id=? and runtime_agent_id=?";try(Connection c=open(client,true);PreparedStatement q=c.prepareStatement(sql)){q.setString(1,client);q.setString(2,userId);q.setString(3,agent);try(ResultSet rs=q.executeQuery()){int out=0;if(rs.next()){out=rs.getInt(1);if(rs.wasNull())out=0;}c.commit();return out;}}catch(Exception e){throw new IllegalStateException("projected version read failed",e);}}
 public void markProjected(String client,String userId,String agent,int version){String sql="update agent_binding a set projected_version=?,projected_at=now() from agent_blueprint b where a.blueprint_id=b.blueprint_id and a.client_code=? and a.user_id=? and a.runtime_agent_id=? and b.status='PUBLISHED' and b.version=?";try(Connection c=open(client,false);PreparedStatement q=c.prepareStatement(sql)){q.setInt(1,version);q.setString(2,client);q.setString(3,userId);q.setString(4,agent);q.setInt(5,version);if(q.executeUpdate()!=1)throw new IllegalStateException("published binding changed during projection");c.commit();}catch(Exception e){throw new IllegalStateException("projected version update failed",e);}}
 private Connection open(String client,boolean readOnly)throws SQLException{Connection c=DriverManager.getConnection(url,user,password);c.setReadOnly(readOnly);c.setAutoCommit(false);try(PreparedStatement set=c.prepareStatement("select set_config('app.client_code',?,true)")){set.setString(1,client);set.execute();}try(Statement role=c.createStatement()){role.execute("set local role agent_runtime");}return c;}
}
