package com.yjiyun.chatflows.runtime.observability;

import java.net.URI;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

/**
 * Best-effort AgentLoop ROA exporter (A22). Three modes (off / stderr / on) plus run_id sampling;
 * any export failure disables only this exporter (A12). Envelope building drops credential-shaped keys.
 * Intentionally duplicated from agent-manager to avoid coupling the two Java modules.
 */
public final class AgentLoopExporter {
 private final String mode,endpoint,key,secret; private final double sampleRate; private final HttpClient http; private volatile boolean enabled=true;
 public AgentLoopExporter(Map<String,String> env){mode=env.getOrDefault("AGENTLOOP_EXPORTER","off").trim().toLowerCase(Locale.ROOT);endpoint=trim(env.get("AGENTLOOP_ENDPOINT"));key=trim(env.get("AGENTLOOP_ACCESS_KEY"));secret=trim(env.get("AGENTLOOP_ACCESS_SECRET"));sampleRate=Double.parseDouble(env.getOrDefault("AGENTLOOP_SAMPLE_RATE","1.0"));if(!Set.of("off","stderr","on").contains(mode))throw new IllegalStateException("AGENTLOOP_EXPORTER must be off, stderr or on");if(!Double.isFinite(sampleRate)||sampleRate<0||sampleRate>1)throw new IllegalStateException("AGENTLOOP_SAMPLE_RATE must be 0.0..1.0");if("on".equals(mode)&&(endpoint==null||key==null||secret==null))throw new IllegalStateException("AgentLoop on mode requires endpoint/access key/access secret");http=HttpClient.newHttpClient();}
 public void emit(String name,Map<String,?> source,String traceparent){Object run=source.get("agentteams.run_id"),fallback=source.get("agentteams.client_code");String bucket=String.valueOf(run!=null?run:fallback!=null?fallback:"unknown");if(!enabled||"off".equals(mode)||!sampled(bucket))return;Map<String,Object> attrs=new LinkedHashMap<>();attrs.put("gen_ai.operation.name","chat");attrs.put("agentteams.agent","agent-runtime");attrs.put("agentteams.trace.link",traceparent==null?"run_id_fallback":"traceparent");attrs.putAll(source);attrs.put("agentteams.usage.scope","run");attrs.put("agentteams.worker_usage_available",false);send(envelope(name,traceparent,attrs));}
 private void send(String body){try{if("stderr".equals(mode)){System.err.println("[agentloop] "+body);return;}String date=DateTimeFormatter.RFC_1123_DATE_TIME.format(ZonedDateTime.now(ZoneOffset.UTC));HttpRequest.Builder request=HttpRequest.newBuilder(URI.create(endpoint)).POST(HttpRequest.BodyPublishers.ofString(body));roaHeaders(endpoint,body,key,secret,date,UUID.randomUUID().toString()).forEach(request::header);http.sendAsync(request.build(),HttpResponse.BodyHandlers.discarding()).thenAccept(response->{if(response.statusCode()/100!=2)disable("HTTP "+response.statusCode());}).exceptionally(error->{disable(error.getClass().getSimpleName());return null;});}catch(Exception error){disable(error.getClass().getSimpleName());}}
 /** Serializes an AgentLoop envelope, dropping credential-shaped keys and non-scalar values. */
 public static String envelope(String name,String traceparent,Map<String,?> attributes){StringBuilder out=new StringBuilder("{\"name\":\"").append(esc(name)).append("\",\"timestamp\":\"").append(Instant.now()).append("\",\"attributes\":{");boolean first=true;for(Map.Entry<String,?> entry:attributes.entrySet()){Object value=entry.getValue();if(sensitive(entry.getKey())||!(value instanceof String||value instanceof Number||value instanceof Boolean))continue;if(!first)out.append(',');first=false;out.append('"').append(esc(entry.getKey())).append("\":");if(value instanceof String text)out.append('"').append(esc(text)).append('"');else out.append(value);}out.append('}');if(traceparent!=null&&!traceparent.isBlank())out.append(",\"traceparent\":\"").append(esc(traceparent)).append('"');return out.append('}').toString();}
 private boolean sampled(String value){if(sampleRate==1)return true;if(sampleRate==0)return false;try{byte[] hash=MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));long bucket=((long)(hash[0]&255)<<24)|((long)(hash[1]&255)<<16)|((long)(hash[2]&255)<<8)|(hash[3]&255);return bucket/4294967296.0<sampleRate;}catch(Exception error){return false;}}
 private void disable(String reason){if(enabled){enabled=false;System.err.println("[agentloop-exporter] disabled: "+reason);}}
 public static Map<String,String> roaHeaders(String endpoint,String body,String key,String secret,String date,String nonce){try{String md5=Base64.getEncoder().encodeToString(MessageDigest.getInstance("MD5").digest(body.getBytes(StandardCharsets.UTF_8)));Map<String,String> acs=new TreeMap<>();acs.put("x-acs-signature-method","HMAC-SHA1");acs.put("x-acs-signature-nonce",nonce);acs.put("x-acs-signature-version","1.0");acs.put("x-acs-version","2026-05-20");StringBuilder canonical=new StringBuilder();acs.forEach((k,v)->canonical.append(k).append(':').append(v).append('\n'));URI uri=URI.create(endpoint);String resource=uri.getRawPath()+(uri.getRawQuery()==null?"":"?"+uri.getRawQuery());String sign="POST\napplication/json\n"+md5+"\napplication/json\n"+date+"\n"+canonical+resource;Mac mac=Mac.getInstance("HmacSHA1");mac.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA1"));Map<String,String> headers=new LinkedHashMap<>();headers.put("accept","application/json");headers.put("content-type","application/json");headers.put("content-md5",md5);headers.put("date",date);headers.putAll(acs);headers.put("authorization","acs "+key+":"+Base64.getEncoder().encodeToString(mac.doFinal(sign.getBytes(StandardCharsets.UTF_8))));return headers;}catch(Exception error){throw new IllegalStateException("AgentLoop ROA signing unavailable",error);}}
 private static boolean sensitive(String key){String normalized=key.toLowerCase(Locale.ROOT).replace('-','_');return segment(normalized,"token")||segment(normalized,"secret")||segment(normalized,"password")||segment(normalized,"authorization")||normalized.contains("api_key")||normalized.contains("access_key");}
 private static boolean segment(String key,String marker){return Arrays.asList(key.split("[._]")).contains(marker);}
 private static String esc(String value){return value.replace("\\","\\\\").replace("\"","\\\"").replace("\r","\\r").replace("\n","\\n");}
 private static String trim(String value){return value==null||value.isBlank()?null:value.trim();}
}
