package com.yjiyun.chatflows.manager.api;
import com.fasterxml.jackson.databind.JsonNode; import com.sun.net.httpserver.*; import com.yjiyun.chatflows.manager.agent.*; import com.yjiyun.chatflows.manager.artifact.TaskArtifactStore; import com.yjiyun.chatflows.manager.control.*; import com.yjiyun.chatflows.manager.matrix.*; import com.yjiyun.chatflows.manager.observability.ManagerTelemetry; import com.yjiyun.chatflows.manager.security.AuthService; import com.yjiyun.chatflows.manager.security.ForbiddenException; import java.io.*; import java.nio.charset.StandardCharsets; import java.util.*; import java.util.regex.*;
public final class OrchestrationController implements HttpHandler {
 private static final String ROOT="/api/v1/orchestrations";
 private final AuthService auth; private final PipelineControlClient pipeline; private final OrchestrationStore store; private final OrchestrationPlanner planner; private final TaskArtifactStore tasks; private final MatrixClient matrix; private final Set<String> leaderIds,humanIds; private final String leaderId; private final String defaultRoom;
 public OrchestrationController(AuthService auth,PipelineControlClient pipeline,OrchestrationStore store,OrchestrationPlanner planner,TaskArtifactStore tasks,MatrixClient matrix,Set<String> leaderIds,Set<String> humanIds,String defaultRoom){this.auth=auth;this.pipeline=pipeline;this.store=store;this.planner=planner;this.tasks=tasks;this.matrix=matrix;this.leaderIds=Set.copyOf(leaderIds);this.humanIds=Set.copyOf(humanIds);if(this.humanIds.isEmpty())throw new IllegalArgumentException("Human allowlist required");this.leaderId=com.yjiyun.chatflows.manager.ManagerComposition.onlyLeader(this.leaderIds);this.defaultRoom=defaultRoom;}
 public void handle(HttpExchange x)throws IOException{try{String path=x.getRequestURI().getPath();if(ROOT.equals(path)||(ROOT+"/").equals(path)){create(x);return;}String suffix=path.startsWith(ROOT+"/")?path.substring(ROOT.length()+1):"";String[] parts=Arrays.stream(suffix.split("/")).filter(part->!part.isBlank()).toArray(String[]::new);if(parts.length==0)throw new NoSuchElementException("endpoint not found");String runId=HttpSupport.id(parts[0]);if(parts.length==1){get(x,runId);return;}if(parts.length==2&&"events".equals(parts[1])){events(x,runId);return;}if(parts.length==2&&"room".equals(parts[1])){room(x,runId);return;}if(parts.length==2&&"approval".equals(parts[1])){approval(x,runId);return;}if(parts.length==2&&"abort".equals(parts[1])){abort(x,runId);return;}if(parts.length==2&&"nudge".equals(parts[1])){nudge(x,runId);return;}throw new NoSuchElementException("endpoint not found");}catch(Exception e){HttpSupport.error(x,e);}finally{x.close();}}
 private void create(HttpExchange x)throws Exception{HttpSupport.method(x,"POST");auth.requireRole(HttpSupport.bearer(x),HttpSupport.header(x,"X-Role"),"orchestrator","admin");String actor=requiredHeader(x,"X-Actor");Map<String,Object> body=HttpSupport.body(x);String client=HttpSupport.required(body,"client_code"),spec=HttpSupport.required(body,"spec");if(!client.matches("[A-Za-z0-9_-]+"))throw new IllegalArgumentException("client_code invalid");String room=body.get("room_id") instanceof String text&&!text.isBlank()?text.trim():defaultRoom;if(room==null||room.isBlank())throw new IllegalArgumentException("room_id required");PipelineControlClient.IssuedRun issued=pipeline.createRun(client,actor,spec);OrchestrationRun run=store.create(issued.runId(),issued.clientCode(),room,planner.mode());planner.start(run,spec);HttpSupport.json(x,202,run.view());}
 private void get(HttpExchange x,String runId)throws IOException{HttpSupport.method(x,"GET");auth.requireRole(HttpSupport.bearer(x),HttpSupport.header(x,"X-Role"),"orchestrator","human","admin","user");OrchestrationRun run=store.require(runId);refresh(run);HttpSupport.json(x,200,run.view());}
 private void room(HttpExchange x,String runId)throws IOException{HttpSupport.method(x,"GET");auth.requireRole(HttpSupport.bearer(x),HttpSupport.header(x,"X-Role"),"orchestrator","human","admin","user");OrchestrationRun run=store.require(runId);try{matrix.join(run.roomId());HttpSupport.json(x,200,RoomTimeline.view(matrix.receive(run.roomId()),run.runId(),run.roomId()));}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IOException("Matrix room interrupted",e);}}
 private void events(HttpExchange x,String runId)throws IOException{HttpSupport.method(x,"GET");auth.requireRole(HttpSupport.bearer(x),HttpSupport.header(x,"X-Role"),"orchestrator","human","admin","user");OrchestrationRun run=store.require(runId);boolean once="1".equals(HttpSupport.query(x).get("once"));x.getResponseHeaders().set("Content-Type","text/event-stream; charset=utf-8");x.getResponseHeaders().set("Cache-Control","no-cache");x.getResponseHeaders().set("X-Accel-Buffering","no");x.sendResponseHeaders(200,0);try(OutputStream out=x.getResponseBody()){long cursor=0,deadline=System.currentTimeMillis()+30000;do{refresh(run);long after=cursor;List<OrchestrationRun.Event> fresh=run.events().stream().filter(event->event.id()>after).toList();if(!fresh.isEmpty()){out.write(sse(fresh).getBytes(StandardCharsets.UTF_8));out.flush();cursor=fresh.get(fresh.size()-1).id();}if(once||"SUCCEEDED".equals(run.view().get("status"))||"ABORTED".equals(run.view().get("status"))||"FAILED".equals(run.view().get("status")))break;try{Thread.sleep(500);}catch(InterruptedException e){Thread.currentThread().interrupt();break;}}while(System.currentTimeMillis()<deadline);}
 }
 private void approval(HttpExchange x,String runId)throws Exception{HttpSupport.method(x,"POST");auth.requireRole(HttpSupport.bearer(x),HttpSupport.header(x,"X-Role"),"human","admin");String actor=requiredHeader(x,"X-Actor");if(!humanIds.contains(actor))throw new ForbiddenException("actor is not an authorized Human");Map<String,Object> body=HttpSupport.body(x);String approvalId=HttpSupport.required(body,"approval_id");if(!(body.get("approved") instanceof Boolean approved))throw new IllegalArgumentException("approved must be boolean");OrchestrationRun run=store.require(runId);JsonNode result=pipeline.approval(runId,approvalId,approved,actor);JsonNode signed=result.path("approval");String proof=signed.path("proof").asText(),decision=signed.path("decision").asText();if(proof.isBlank()||decision.isBlank())throw new IOException("Nest approval response missing signed proof");matrix.join(run.roomId());matrix.sendMention(run.roomId(),leaderId,"@chatflows-leader APPROVAL_PROOF run_id="+runId+" approval_id="+approvalId+" decision="+decision+" proof="+proof);run.approval(approvalId,approved,actor);HttpSupport.json(x,200,result);}
 private void abort(HttpExchange x,String runId)throws Exception{HttpSupport.method(x,"POST");auth.requireRole(HttpSupport.bearer(x),HttpSupport.header(x,"X-Role"),"admin");String actor=requiredHeader(x,"X-Actor");Map<String,Object> body=HttpSupport.body(x);String reason=HttpSupport.required(body,"reason");if(reason.length()>500)throw new IllegalArgumentException("reason too long");OrchestrationRun run=store.require(runId);JsonNode result=pipeline.abort(runId,actor,reason);if(!"ABORTED".equals(result.path("status").asText()))throw new IOException("Nest abort response missing ABORTED status");run.abort(actor,reason);emitRunSummaryOnce(run,"ABORTED","已中止：\n"+reason);matrix.join(run.roomId());matrix.sendMention(run.roomId(),leaderId,"@chatflows-leader RUN_ABORTED run_id="+runId+" reason="+reason);HttpSupport.json(x,200,run.view());}
 /**
  * RUN_BLOCKED 里最常见的一类（driver_not_found/连接类）几秒后就自愈：MCP 长连接空闲
  * 超时触发自动重连，Worker 撞上那个窄窗口就报失败并放弃，但重连早就成功了。这个端点
  * 不碰 Nest 状态（run 本来就没有真 abort），只在 Team Room 补发一条 @Leader 的提醒，
  * 让它重新派活/重试当前阶段——等价于人工在 Team Room 手动敲一条消息。
  */
 private void nudge(HttpExchange x,String runId)throws Exception{HttpSupport.method(x,"POST");auth.requireRole(HttpSupport.bearer(x),HttpSupport.header(x,"X-Role"),"human","admin");String actor=requiredHeader(x,"X-Actor");if(!humanIds.contains(actor))throw new ForbiddenException("actor is not an authorized Human");OrchestrationRun run=store.require(runId);matrix.join(run.roomId());matrix.sendMention(run.roomId(),leaderId,"@chatflows-leader run_id="+runId+" 的 MCP 已确认恢复健康，请重新派发/重试当前阶段（若已拿到部分产物如 blueprintId，直接原样复用重试下一步即可，不需要重新走前面已完成的步骤）。不需要 abort 重开这个 run。");HttpSupport.json(x,200,run.view());}
 private static String requiredHeader(HttpExchange x,String name){String value=HttpSupport.header(x,name);if(value.isBlank())throw new IllegalArgumentException(name+" required");return value;}
 private void refresh(OrchestrationRun run)throws IOException{try{for(String approvalId:RunSupervisor.requests(matrix.receive(run.roomId()),run.runId(),leaderIds))run.pendingApproval(approvalId);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IOException("Matrix refresh interrupted",e);}Optional<String> result=tasks.readResultIfExists(run.runId());if(result.isEmpty())return;String body=result.get();RunSupervisor.Result terminal=RunSupervisor.terminal(body,run.runId());if(terminal!=null&&"SUCCEEDED".equals(terminal.status()))try{Optional<String> rejected=CompletionGate.rejectReason(terminal,pipeline.runSnapshot(run.runId()));if(rejected.isPresent()){run.artifact("result.md.rejected","REJECTED",rejected.get());return;}}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IOException("Nest completion check interrupted",e);}for(RunSupervisor.ArtifactPointer pointer:RunSupervisor.artifacts(body))run.artifact(pointer.kind(),"v"+pointer.version(),"Leader result.md pointer");if(run.artifact("result.md",terminal==null?"AVAILABLE":terminal.status(),body.substring(0,Math.min(160,body.length()))))run.event("leader_report",Map.of("status",terminal==null?"AVAILABLE":terminal.status()));planner.resume(run,body);if(terminal!=null){emitRunSummaryOnce(run,terminal.status(),body);run.terminal(terminal.status(),terminal.summary());}}
 private void emitRunSummaryOnce(OrchestrationRun run,String status,String output)throws IOException{if(!run.artifact("manager.telemetry.summary",status,run.runId()))return;ManagerTelemetry.emitRunSummary(run.runId(),run.clientCode(),loadRunInput(run.runId()),output,status);}
 private String loadRunInput(String runId)throws IOException{String spec=tasks.readSpec(runId);Matcher matcher=Pattern.compile("(?s)^---\\R.*?\\R---\\R?").matcher(spec);return matcher.find()?spec.substring(matcher.end()).trim():spec.trim();}
 static String sse(List<OrchestrationRun.Event> events)throws IOException{StringBuilder out=new StringBuilder();for(OrchestrationRun.Event event:events)out.append("id: ").append(event.id()).append("\nevent: ").append(event.type()).append("\ndata: ").append(HttpSupport.JSON.writeValueAsString(event)).append("\n\n");return out.toString();}
}
